/* ============================================================
   CAREMAP MORRIS — Resource Data
   50 community organizations in Morris County, NJ
============================================================ */

const RESOURCES = [
  {
    id: 1,
    title: "Community Food Bank of Morris County",
    category: "food",
    town: "Morris Township",
    address: "2 Executive Dr, Morris Township, NJ 07960",
    phone: "(973) 538-8049",
    website: "https://cfbmc.org",
    hours: "Mon–Fri 9am–4pm",
    shortDesc: "The largest food assistance organization in Morris County, providing groceries and meals to thousands of food-insecure residents.",
    longDesc: "The Community Food Bank of Morris County has served the region since 1977, distributing millions of pounds of food annually to individuals and families. They operate a network of partner pantries and offer a client-choice model where visitors select their own groceries. They also run mobile food pantries, senior nutrition programs, and emergency boxes for families in crisis. No income verification is required for a first visit.",
    tags: ["Food Pantry", "Groceries", "Mobile Pantry", "No Appointment"],
    services: ["food", "emergency"],
    saves: 0
  },
  {
    id: 2,
    title: "Homeless Solutions",
    category: "housing",
    town: "Morristown",
    address: "85 Parsippany Rd, Morristown, NJ 07960",
    phone: "(973) 540-0111",
    website: "https://homelesssolutions.org",
    hours: "24/7 Emergency Line",
    shortDesc: "Comprehensive homeless services including emergency shelter, transitional housing, and case management in Morris County.",
    longDesc: "Homeless Solutions operates three emergency shelters and multiple transitional housing facilities in Morris County. Their highly trained case managers work one-on-one with clients to address housing instability, mental health, substance use, and employment barriers. Programs include rapid rehousing assistance, a veterans' shelter, a family shelter, and a day resource center open to all. They also run a warming center in winter months.",
    tags: ["Emergency Shelter", "Housing Navigation", "Case Management", "Veterans"],
    services: ["housing", "emergency", "counseling"],
    saves: 0
  },
  {
    id: 3,
    title: "Domestic Violence Program of Morris County (dv4life)",
    category: "domestic-violence",
    town: "Morristown",
    address: "PO Box 1437, Morristown, NJ 07962",
    phone: "(973) 267-4763",
    website: "https://dv4life.org",
    hours: "24/7 Hotline",
    shortDesc: "Confidential shelter, counseling, and legal advocacy for survivors of domestic violence and their children.",
    longDesc: "dv4life is Morris County's primary domestic violence organization, providing a full continuum of services to survivors and their families. Their safe house offers emergency shelter for up to 30 days, with extensions available. Services include crisis counseling, safety planning, court accompaniment, legal advocacy, children's programming, and transitional housing. All services are free and completely confidential. A 24-hour bilingual hotline is available.",
    tags: ["24/7 Hotline", "Safe House", "Legal Advocacy", "Children's Services", "Bilingual"],
    services: ["counseling", "emergency", "legal", "housing"],
    saves: 0
  },
  {
    id: 4,
    title: "Family Promise of Morris County",
    category: "housing",
    town: "Morristown",
    address: "36 Elm St, Morristown, NJ 07960",
    phone: "(973) 326-7189",
    website: "https://familypromisemorriscounty.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Shelter and housing stability programs specifically for families with children experiencing homelessness.",
    longDesc: "Family Promise of Morris County is dedicated to helping homeless and low-income families achieve sustainable independence. Their Interfaith Hospitality Network rotates families through participating congregations while case managers provide intensive support. Programs include day resource services, financial literacy, employment coaching, and an afterschool program for children in transitional housing. The organization places a strong emphasis on family unity and child wellbeing.",
    tags: ["Family Shelter", "Children's Programs", "Employment Support", "Housing Stability"],
    services: ["housing", "emergency", "employment"],
    saves: 0
  },
  {
    id: 5,
    title: "St. John's Soup Kitchen",
    category: "food",
    town: "Morristown",
    address: "5 Perry St, Morristown, NJ 07960",
    phone: "(973) 538-0760",
    website: "https://stjohnssoupkitchen.org",
    hours: "Mon–Sat 11:30am–12:30pm",
    shortDesc: "Hot daily meals served to anyone in need, no questions asked, in the heart of Morristown.",
    longDesc: "St. John's Soup Kitchen has been serving hot, nutritious lunches to Morris County residents in need since 1982. Their all-volunteer operation serves hundreds of meals every weekday in a welcoming, dignified setting. No ID or proof of need is required. The kitchen also distributes bread and pastries from local bakeries, provides birthday meals, and offers seasonal holiday dinners. Volunteer opportunities are available for groups and individuals.",
    tags: ["Hot Meals", "Daily Service", "No ID Required", "Volunteers Welcome"],
    services: ["food"],
    saves: 0
  },
  {
    id: 6,
    title: "Morris County Hunger Project",
    category: "food",
    town: "Flanders",
    address: "3 Flanders-Netcong Rd, Flanders, NJ 07836",
    phone: "(973) 252-1111",
    website: "https://morriscountyhungerproject.org",
    hours: "Tue & Thu 10am–12pm",
    shortDesc: "Emergency food pantry serving residents across western Morris County with groceries and household essentials.",
    longDesc: "The Morris County Hunger Project provides emergency food assistance to residents of Mount Olive, Netcong, Flanders, and surrounding communities. Operating out of a dedicated warehouse, they distribute weekly grocery packages tailored to household size, with an emphasis on fresh produce, proteins, and culturally appropriate foods. They also offer a summer backpack program for school-aged children and holiday food baskets.",
    tags: ["Food Pantry", "Emergency Groceries", "Summer Program", "Western Morris County"],
    services: ["food", "emergency"],
    saves: 0
  },
  {
    id: 7,
    title: "Interfaith Food Pantry",
    category: "food",
    town: "Morris Plains",
    address: "2 Executive Dr, Morris Plains, NJ 07950",
    phone: "(973) 605-0060",
    website: "https://interfaithfoodpantry.org",
    hours: "Mon, Wed, Fri 9am–12pm; Tue 6–8pm",
    shortDesc: "Client-choice pantry offering fresh produce, dairy, proteins, and pantry staples to Morris County families.",
    longDesc: "The Interfaith Food Pantry operates a client-choice model, allowing visitors to select the foods that work for their family's needs and preferences. The pantry carries over 200 items including fresh fruits and vegetables, dairy, meat, canned goods, and personal care products. They also have a kosher section and accommodate dietary restrictions. Delivery is available for homebound seniors. New clients must bring proof of Morris County residence.",
    tags: ["Client Choice", "Fresh Produce", "Kosher Options", "Senior Delivery"],
    services: ["food"],
    saves: 0
  },
  {
    id: 8,
    title: "Journey Program — Mental Health Association",
    category: "mental-health",
    town: "Parsippany",
    address: "100 E Hanover Ave, Cedar Knolls, NJ 07927",
    phone: "(973) 334-3921",
    website: "https://mhanjmorris.org",
    hours: "Mon–Fri 8:30am–4:30pm",
    shortDesc: "Mental health counseling, crisis support, and psychiatric services for adults in Morris County on a sliding fee scale.",
    longDesc: "The Mental Health Association of Essex and Morris provides outpatient mental health services to adults regardless of income or insurance status. Services include individual therapy, group counseling, psychiatric evaluations, medication management, and crisis intervention. The Journey Program specifically serves adults with serious mental illness, offering case management and skill-building to support recovery and community integration.",
    tags: ["Counseling", "Psychiatric Services", "Sliding Scale", "Crisis Support"],
    services: ["counseling", "emergency"],
    saves: 0
  },
  {
    id: 9,
    title: "Providence House",
    category: "housing",
    town: "Dover",
    address: "22 N Sussex St, Dover, NJ 07801",
    phone: "(973) 366-0057",
    website: "https://providencehouseofmorriscounty.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Transitional housing and supportive services for women with children fleeing poverty and homelessness in eastern Morris County.",
    longDesc: "Providence House offers transitional housing specifically for women with children who are experiencing homelessness or housing instability. Residents can stay for up to two years while working with case managers toward permanent housing. On-site services include parenting classes, financial counseling, life skills workshops, and children's tutoring. The organization also operates a thrift store that generates revenue and provides affordable goods to the community.",
    tags: ["Women & Children", "Transitional Housing", "Life Skills", "2-Year Program"],
    services: ["housing", "counseling", "employment"],
    saves: 0
  },
  {
    id: 10,
    title: "Catholic Charities of the Diocese of Paterson",
    category: "social-services",
    town: "Rockaway",
    address: "24 DeHart St, Morristown, NJ 07960",
    phone: "(973) 279-7100",
    website: "https://catholiccharitiespatdio.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Broad social services including food assistance, immigration services, mental health counseling, and emergency financial aid.",
    longDesc: "Catholic Charities serves people of all faiths across Morris and Passaic counties. Their Morristown office provides emergency food assistance, utility and rent help, immigration legal services, mental health counseling, and programs for seniors and people with disabilities. They are a primary resource for undocumented residents who may not qualify for government assistance. Language services are available in Spanish, Portuguese, and other languages.",
    tags: ["Emergency Aid", "Immigration Services", "Bilingual", "All Faiths Welcome"],
    services: ["food", "emergency", "legal", "counseling"],
    saves: 0
  },
  {
    id: 11,
    title: "Norwescap Food Pantry",
    category: "food",
    town: "Netcong",
    address: "350 Marshall St, Phillipsburg, NJ 08865",
    phone: "(908) 454-7000",
    website: "https://norwescap.org",
    hours: "Mon–Fri 9am–3pm",
    shortDesc: "Community action agency providing food assistance, WIC services, and SNAP enrollment support to Morris County residents.",
    longDesc: "Norwescap is a community action agency providing food pantry services, WIC (Women, Infants, and Children) nutrition program, SNAP enrollment assistance, and Head Start early education. Their Morris County locations serve residents in the western parts of the county, helping connect low-income individuals and families to benefits they may not know they qualify for. Staff can provide application assistance for multiple assistance programs in a single visit.",
    tags: ["Food Pantry", "WIC", "SNAP Enrollment", "Head Start"],
    services: ["food", "benefits-navigation"],
    saves: 0
  },
  {
    id: 12,
    title: "New Hope Foundation",
    category: "substance-use",
    town: "Marlboro",
    address: "22 Saw Mill Rd, Marlboro, NJ 07746",
    phone: "(973) 366-0172",
    website: "https://newhopefoundation.org",
    hours: "24/7 Admissions",
    shortDesc: "Residential substance use treatment with detoxification, rehabilitation, and recovery support for Morris County adults.",
    longDesc: "New Hope Foundation provides a full continuum of substance use disorder treatment for adults, including medically supervised detox, short-term residential rehabilitation, long-term residential treatment, and outpatient services. Their licensed clinical staff offer individual and group therapy, relapse prevention planning, dual diagnosis treatment, and family counseling. Sliding scale fees and insurance are accepted. Transportation assistance may be available for Morris County residents.",
    tags: ["Detox", "Residential Treatment", "Outpatient", "Dual Diagnosis"],
    services: ["counseling", "emergency"],
    saves: 0
  },
  {
    id: 13,
    title: "CHAP — Children's Home and Adolescent Programs",
    category: "youth",
    town: "Morristown",
    address: "51 James St, Morristown, NJ 07960",
    phone: "(973) 540-0550",
    website: "https://chapnj.org",
    hours: "Mon–Fri 8am–6pm",
    shortDesc: "Child welfare, foster care, and youth development services for at-risk children and families across Morris County.",
    longDesc: "CHAP provides a wide range of child welfare services including therapeutic foster care, adoption services, family preservation, mentoring, and after-school programs. They work with children who have experienced trauma, abuse, or neglect, offering trauma-informed care and wrap-around services for the whole family. Their Youth Advocates Program pairs youth in foster care with trained mentors who provide guidance and support.",
    tags: ["Foster Care", "Youth Mentoring", "Trauma-Informed", "After-School"],
    services: ["counseling", "youth"],
    saves: 0
  },
  {
    id: 14,
    title: "Neighborhood House",
    category: "social-services",
    town: "Morristown",
    address: "12 Flagler St, Morristown, NJ 07960",
    phone: "(973) 538-4180",
    website: "https://neighborhoodhousenj.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Community center offering adult education, ESL classes, job training, and youth programs for low-income Morristown families.",
    longDesc: "Neighborhood House has been a pillar of the Morristown community for over a century. They offer ESL and literacy classes, GED preparation, workforce development, job placement assistance, youth after-school programming, and summer camps. Their services particularly support immigrant and refugee populations. The organization also provides case management and links clients to housing, benefits, and health care resources.",
    tags: ["ESL Classes", "Job Training", "Youth Programs", "Immigrant Services"],
    services: ["education", "employment", "youth"],
    saves: 0
  },
  {
    id: 15,
    title: "Cornerstone Family Programs",
    category: "mental-health",
    town: "Parsippany",
    address: "301 Changebridge Rd, Montville, NJ 07045",
    phone: "(973) 334-5730",
    website: "https://cornerstonefamilyprograms.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Family therapy, child counseling, and parenting support programs for Morris County families in crisis and at risk.",
    longDesc: "Cornerstone Family Programs provides therapeutic and educational services to children, adolescents, and families throughout northern New Jersey. Their licensed therapists specialize in trauma, anxiety, depression, ADHD, and family conflict. Specific programs include Functional Family Therapy for court-involved youth, home-based intervention services, parent training, and a dedicated therapeutic nursery school for young children with developmental or behavioral challenges.",
    tags: ["Family Therapy", "Child Counseling", "Parenting Support", "Home-Based Services"],
    services: ["counseling", "youth"],
    saves: 0
  },
  {
    id: 16,
    title: "Morris Habitat for Humanity",
    category: "housing",
    town: "Wharton",
    address: "111 N Main St, Wharton, NJ 07885",
    phone: "(973) 366-4838",
    website: "https://morrishabitat.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Affordable homeownership construction and home repair services for low- and moderate-income Morris County residents.",
    longDesc: "Morris Habitat for Humanity partners with families to build and renovate affordable homes in Morris County. Qualifying families contribute 'sweat equity' hours and receive a no-interest mortgage. Their Critical Home Repair program also serves elderly and disabled homeowners who need essential repairs to stay safely in their homes. Volunteers of all skill levels are welcome to help with construction, ReStore operations, and office support.",
    tags: ["Affordable Housing", "Home Repair", "Volunteer Construction", "No-Interest Mortgage"],
    services: ["housing"],
    saves: 0
  },
  {
    id: 17,
    title: "Center for Great Expectations",
    category: "substance-use",
    town: "Somerset",
    address: "652 Cranbury Rd, Somerset, NJ 08873",
    phone: "(908) 271-1110",
    website: "https://cge-nj.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Residential and outpatient substance use recovery services for pregnant women, mothers, and families.",
    longDesc: "Center for Great Expectations specializes in substance use treatment for women, with a particular focus on pregnant women and mothers with children. Their residential programs allow mothers to keep their children with them during treatment. Services include medically supervised detox, trauma therapy, parenting skills, domestic violence counseling, and housing assistance for program graduates. They operate in Somerset and Morris counties.",
    tags: ["Women's Treatment", "Mothers & Children", "Residential", "Trauma-Informed"],
    services: ["counseling", "housing", "emergency"],
    saves: 0
  },
  {
    id: 18,
    title: "NORWESCAP WIC Program",
    category: "food",
    town: "Mount Olive",
    address: "204 Flanders-Drakestown Rd, Mount Olive, NJ 07836",
    phone: "(908) 454-7000",
    website: "https://norwescap.org/wic",
    hours: "Mon–Fri 9am–4pm",
    shortDesc: "WIC nutrition benefits for pregnant women, new mothers, infants, and children up to age 5 in western Morris County.",
    longDesc: "The WIC (Women, Infants, and Children) program provides supplemental nutrition benefits, breastfeeding support, nutrition counseling, and referrals to health care for income-eligible pregnant women, postpartum women, and children under 5. Norwescap's Mount Olive WIC office serves western Morris County residents. Benefits come on an EBT card usable at participating grocery stores. Bilingual staff are available.",
    tags: ["WIC Benefits", "Infant Formula", "Breastfeeding Support", "Nutrition Counseling"],
    services: ["food", "health"],
    saves: 0
  },
  {
    id: 19,
    title: "ARC of Morris County",
    category: "disability",
    town: "Randolph",
    address: "2 Ridgedale Ave, Randolph, NJ 07869",
    phone: "(973) 884-5272",
    website: "https://arcofmorris.org",
    hours: "Mon–Fri 8:30am–4:30pm",
    shortDesc: "Employment, residential, and day programs for adults and children with intellectual and developmental disabilities.",
    longDesc: "ARC of Morris County has provided supports and services to people with intellectual and developmental disabilities for over 60 years. Programs include supported employment, group homes, day programs, family support, respite care, and early intervention for young children. Their vocational training and job placement services help adults with disabilities find meaningful, integrated employment in the community.",
    tags: ["Developmental Disabilities", "Supported Employment", "Residential Programs", "Respite Care"],
    services: ["disability", "employment"],
    saves: 0
  },
  {
    id: 20,
    title: "Sunrise House Treatment Center",
    category: "substance-use",
    town: "Lafayette",
    address: "37 Sunset Inn Rd, Lafayette, NJ 07848",
    phone: "(973) 383-5507",
    website: "https://sunrisehouserehab.com",
    hours: "24/7 Admissions",
    shortDesc: "Residential substance abuse treatment center serving Morris and Sussex county residents with medical detox and rehabilitation.",
    longDesc: "Sunrise House offers medically supervised detoxification, short-term residential rehabilitation, and transitional living for adults with substance use disorders. Their multidisciplinary team provides individual therapy, group counseling, family therapy, and medication-assisted treatment when appropriate. Insurance is accepted, and a sliding fee scale is available for uninsured residents of northern New Jersey.",
    tags: ["Residential Rehab", "Medical Detox", "Insurance Accepted", "Sliding Scale"],
    services: ["counseling", "emergency"],
    saves: 0
  },
  {
    id: 21,
    title: "Morris County Food Pantry Coalition",
    category: "food",
    town: "Morristown",
    address: "12 Schuyler Pl, Morristown, NJ 07960",
    phone: "(973) 285-6885",
    website: "https://morriscounty.gov",
    hours: "By Appointment",
    shortDesc: "County-coordinated network linking residents to their nearest food pantry and emergency food resources.",
    longDesc: "The Morris County Food Pantry Coalition is a county-administered network that coordinates food distribution across more than 40 member food pantries. Staff can help connect residents to the nearest pantry based on their location and schedule. They also manage emergency food referrals for residents in acute crisis, coordinate food drives, and maintain a database of current pantry hours and requirements.",
    tags: ["Pantry Referrals", "County Network", "Emergency Food", "40+ Locations"],
    services: ["food", "emergency"],
    saves: 0
  },
  {
    id: 22,
    title: "Legal Services of Northwest Jersey",
    category: "legal",
    town: "Morristown",
    address: "91 South St, Morristown, NJ 07960",
    phone: "(973) 285-6911",
    website: "https://lsnj.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Free civil legal aid for low-income Morris County residents facing housing, family, benefits, and consumer law issues.",
    longDesc: "Legal Services of Northwest Jersey provides free civil legal representation and advice to income-eligible residents throughout Morris County. They handle cases involving eviction, foreclosure, domestic violence restraining orders, child custody, public benefits, consumer debt, and immigration. Staff attorneys and paralegals also conduct community education workshops and outreach at partner organizations. Walk-in clinics are available at several county locations.",
    tags: ["Free Legal Aid", "Eviction Defense", "Family Law", "Benefits Appeals"],
    services: ["legal"],
    saves: 0
  },
  {
    id: 23,
    title: "Zufall Health Center",
    category: "health",
    town: "Dover",
    address: "63 Elm St, Dover, NJ 07801",
    phone: "(973) 328-0300",
    website: "https://zufallhealth.org",
    hours: "Mon–Fri 8am–8pm; Sat 8am–1pm",
    shortDesc: "Federally Qualified Health Center providing primary, dental, and behavioral health care regardless of ability to pay.",
    longDesc: "Zufall Health is a Federally Qualified Health Center with multiple locations in Morris County, serving patients regardless of income, insurance status, or immigration status. Services include adult and pediatric primary care, dental care, OB/GYN, behavioral health counseling, substance use treatment, nutrition counseling, and pharmacy. They offer a sliding fee discount program based on household income and family size.",
    tags: ["Primary Care", "Dental", "Sliding Fee", "No Immigration Status Required"],
    services: ["health", "counseling"],
    saves: 0
  },
  {
    id: 24,
    title: "Family Resource Network",
    category: "disability",
    town: "Parsippany",
    address: "1515 US Rte 46, Parsippany, NJ 07054",
    phone: "(973) 263-0020",
    website: "https://frnj.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Information, referral, and advocacy services for people with disabilities and their families in Morris and Sussex counties.",
    longDesc: "Family Resource Network (FRN) is a nonprofit information and referral service dedicated to individuals with developmental and physical disabilities. Staff help families navigate the complex system of state and county disability services, including Division of Developmental Disabilities (DDD) eligibility, special education advocacy, respite care, housing options, and transition planning for young adults. All services are free of charge.",
    tags: ["Disability Navigation", "DDD Services", "Special Education", "Family Support"],
    services: ["disability", "benefits-navigation"],
    saves: 0
  },
  {
    id: 25,
    title: "NJ Coalition Against Sexual Assault — Morris County",
    category: "domestic-violence",
    town: "Morristown",
    address: "2 Convent Station, Morristown, NJ 07961",
    phone: "(973) 455-0921",
    website: "https://njcasa.org",
    hours: "24/7 Crisis Hotline",
    shortDesc: "Free, confidential counseling, advocacy, and crisis support for survivors of sexual violence in Morris County.",
    longDesc: "The Morris County Sexual Assault Response and Care Center provides trauma-informed services to survivors of sexual assault and abuse. Services include a 24-hour crisis hotline, hospital accompaniment, free medical forensic exams, individual and group therapy, legal advocacy, and referrals to safe housing. Advocates are available to accompany survivors through police reporting and court proceedings at no cost.",
    tags: ["Sexual Assault", "24/7 Hotline", "Crisis Counseling", "Legal Advocacy", "Confidential"],
    services: ["counseling", "emergency", "legal"],
    saves: 0
  },
  {
    id: 26,
    title: "Growing Stage Theatre — Youth Programs",
    category: "youth",
    town: "Netcong",
    address: "268 Main St, Netcong, NJ 07857",
    phone: "(973) 347-4946",
    website: "https://growingstage.com",
    hours: "Varies by program",
    shortDesc: "Arts-based youth programming and accessible performances for children of all abilities in the Morris County area.",
    longDesc: "Growing Stage Theatre offers educational theater programs for youth across Morris County, including after-school drama clubs, summer theater camps, workshops for schools, and sensory-friendly performances for children with autism and other disabilities. Scholarship assistance is available for families who cannot afford program fees, ensuring all children have access to creative arts education.",
    tags: ["Youth Arts", "Sensory-Friendly", "After-School", "Scholarships Available"],
    services: ["youth", "education"],
    saves: 0
  },
  {
    id: 27,
    title: "Homeless Veterans Initiative — Morris County",
    category: "housing",
    town: "Morristown",
    address: "30 Schuyler Pl, Morristown, NJ 07960",
    phone: "(973) 285-6868",
    website: "https://morriscountynj.gov/veterans",
    hours: "Mon–Fri 8:30am–4:30pm",
    shortDesc: "County-run outreach and housing placement services specifically for homeless veterans in Morris County.",
    longDesc: "Morris County's Division of Veteran Services operates a dedicated outreach team to identify and assist homeless veterans throughout the county. Services include emergency shelter referrals, HUD-VASH voucher enrollment, benefits navigation (VA pension, disability compensation), connection to VA health care, and linkage to VA mental health and substance use programs. The office also coordinates with Homeless Solutions' dedicated veteran shelter.",
    tags: ["Veterans", "Emergency Shelter", "VA Benefits", "Housing Vouchers"],
    services: ["housing", "emergency", "benefits-navigation"],
    saves: 0
  },
  {
    id: 28,
    title: "Mount Olive Food Pantry",
    category: "food",
    town: "Mount Olive",
    address: "2 S Salem St, Flanders, NJ 07836",
    phone: "(973) 691-8662",
    website: "",
    hours: "Wed 5–7pm; Sat 9am–12pm",
    shortDesc: "All-volunteer food pantry providing grocery assistance to residents of the Mount Olive Township area.",
    longDesc: "The Mount Olive Food Pantry is a community-run, all-volunteer organization serving residents of Mount Olive Township with free grocery boxes. Clients can visit twice per month and receive items based on family size. The pantry accepts walk-ins during operating hours with proof of Mount Olive residency. Donations of non-perishable food and personal care items are always welcome, and volunteers are needed for distribution shifts.",
    tags: ["Walk-In", "Twice Monthly", "Mount Olive Residents", "Volunteer-Run"],
    services: ["food"],
    saves: 0
  },
  {
    id: 29,
    title: "Deirdre's House — Child Advocacy Center",
    category: "youth",
    town: "Parsippany",
    address: "3 Executive Campus #100, Cherry Hill, NJ 08002",
    phone: "(973) 884-1480",
    website: "https://deirdrehouse.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Child advocacy center providing trauma-informed forensic interviews and support for child abuse survivors and their families.",
    longDesc: "Deirdre's House is Morris County's child advocacy center, providing a safe, child-friendly environment for forensic interviews when child abuse is suspected. They coordinate a multidisciplinary team including law enforcement, child protective services, and prosecutors to reduce re-traumatization. Services include medical exams, mental health referrals, case management for families, and court preparation. The center also offers community prevention education.",
    tags: ["Child Abuse", "Forensic Interviews", "Trauma-Informed", "Family Support"],
    services: ["counseling", "youth", "legal"],
    saves: 0
  },
  {
    id: 30,
    title: "Visiting Nurse Association of Northern NJ",
    category: "health",
    town: "Whippany",
    address: "930 Harvest Dr, Blue Bell, PA 19422",
    phone: "(973) 538-5454",
    website: "https://vnanorthern.org",
    hours: "Mon–Fri 8am–5pm; After-hours on call",
    shortDesc: "Home health care, hospice, and senior wellness services for homebound Morris County residents.",
    longDesc: "The Visiting Nurse Association of Northern NJ provides skilled nursing care, physical therapy, occupational therapy, speech therapy, and personal care aide services in the home for eligible patients. They also operate a hospice program for terminally ill patients and their families. Their Community Health program offers wellness screenings, flu clinics, and caregiver support groups throughout Morris County. Medicaid, Medicare, and most insurances are accepted.",
    tags: ["Home Health Care", "Hospice", "Senior Services", "Therapy"],
    services: ["health"],
    saves: 0
  },
  {
    id: 31,
    title: "Spanish Community Services of Morris County",
    category: "social-services",
    town: "Morristown",
    address: "16 Flagler St, Morristown, NJ 07960",
    phone: "(973) 984-0777",
    website: "https://scs-mc.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Bilingual social services, emergency assistance, and immigration legal support for the Latino community in Morris County.",
    longDesc: "Spanish Community Services provides a wide range of bilingual services to the Latino community of Morris County. Programs include immigration legal consultations, emergency food and utility assistance, ESL classes, workforce development, health navigation, and citizenship preparation. Their team of bilingual social workers and case managers help families navigate government services, schools, and healthcare. Walk-in hours are available on Tuesday mornings.",
    tags: ["Bilingual", "Immigration Services", "ESL", "Emergency Assistance"],
    services: ["food", "legal", "education", "emergency", "employment"],
    saves: 0
  },
  {
    id: 32,
    title: "Senior Services of Morris County",
    category: "senior",
    town: "Morristown",
    address: "340 W Hanover Ave, Morristown, NJ 07960",
    phone: "(973) 285-6848",
    website: "https://morriscountynj.gov/seniors",
    hours: "Mon–Fri 8:30am–4:30pm",
    shortDesc: "County-administered programs providing meals, transportation, benefits enrollment, and social engagement for Morris County seniors.",
    longDesc: "Morris County's Division of Senior Services coordinates a comprehensive array of programs for adults 60 and older. Services include Meals on Wheels, congregate dining at senior centers, non-emergency medical transportation, PAAD prescription assistance, Medicare counseling through SHIP, caregiver support, legal services, and recreational programming. Staff can help seniors determine eligibility for multiple programs in a single appointment.",
    tags: ["Meals on Wheels", "Transportation", "Medicare Counseling", "Senior Centers"],
    services: ["food", "health", "benefits-navigation"],
    saves: 0
  },
  {
    id: 33,
    title: "Morristown Neighborhood House — ESL Program",
    category: "education",
    town: "Morristown",
    address: "12 Flagler St, Morristown, NJ 07960",
    phone: "(973) 538-4180",
    website: "https://neighborhoodhousenj.org/esl",
    hours: "Mon–Thu evenings; Sat mornings",
    shortDesc: "Free and low-cost ESL, GED, and adult literacy classes for immigrant and low-income adults in Morristown.",
    longDesc: "The Morristown Neighborhood House offers one of the region's most robust adult education programs, with multiple levels of ESL instruction from beginner to advanced, GED preparation, and a basic literacy program. Classes are offered in the evenings and on Saturday mornings to accommodate working adults. Childcare is provided during select class sessions. All teachers are certified and classes are free or very low cost for qualifying students.",
    tags: ["ESL", "GED Prep", "Adult Literacy", "Evening Classes", "Free"],
    services: ["education"],
    saves: 0
  },
  {
    id: 34,
    title: "InClusion Network",
    category: "disability",
    town: "Flanders",
    address: "4 Campbell Blvd, Flanders, NJ 07836",
    phone: "(973) 927-0162",
    website: "https://inclusionnetwork.org",
    hours: "Mon–Fri 9am–4pm",
    shortDesc: "Job coaching, day habilitation, and community integration services for adults with intellectual disabilities in western Morris County.",
    longDesc: "InClusion Network provides person-centered day programs and supported employment services for adults with intellectual and developmental disabilities. Their community-based day habilitation program focuses on independence, socialization, and meaningful daily activities. Supported employment specialists work with local businesses to create job opportunities and provide on-the-job coaching. Transportation to programs is available for participants.",
    tags: ["Day Programs", "Supported Employment", "Job Coaching", "Transportation"],
    services: ["disability", "employment"],
    saves: 0
  },
  {
    id: 35,
    title: "Morristown Medical Center Financial Assistance",
    category: "health",
    town: "Morristown",
    address: "100 Madison Ave, Morristown, NJ 07960",
    phone: "(973) 971-5000",
    website: "https://atlantichealth.org/financial-assistance",
    hours: "Mon–Fri 8am–5pm",
    shortDesc: "Hospital financial assistance and charity care programs for uninsured and underinsured Morris County patients.",
    longDesc: "Morristown Medical Center offers a robust charity care and financial assistance program for patients who are uninsured, underinsured, or unable to pay their medical bills. Based on household income and family size, patients may receive 100% free care or a significant discount. Hospital social workers can assist patients with charity care applications, Medicaid enrollment, and connections to community health resources. Assistance is available for both emergency and planned medical services.",
    tags: ["Charity Care", "Hospital Financial Aid", "Uninsured Patients", "Medicaid Enrollment"],
    services: ["health", "benefits-navigation"],
    saves: 0
  },
  {
    id: 36,
    title: "Parsippany Food Pantry",
    category: "food",
    town: "Parsippany",
    address: "3009 Route 46 E, Parsippany, NJ 07054",
    phone: "(973) 334-1234",
    website: "",
    hours: "Tue & Sat 10am–12pm",
    shortDesc: "Volunteer-run food pantry serving Parsippany residents with non-perishable groceries and household essentials.",
    longDesc: "The Parsippany Food Pantry is an independent, volunteer-run organization providing free grocery boxes to Parsippany-Troy Hills residents in need. Clients can visit once per month and receive a package tailored to their household size. Proof of Parsippany residency is required. The pantry relies entirely on community donations and volunteers — food drives, monetary donations, and distribution volunteers are always welcome.",
    tags: ["Monthly Pantry", "Parsippany Residents", "Volunteer-Run", "Donations Needed"],
    services: ["food"],
    saves: 0
  },
  {
    id: 37,
    title: "Crossroads Programs",
    category: "youth",
    town: "Flemington",
    address: "120 W Main St, Flemington, NJ 08822",
    phone: "(908) 788-5881",
    website: "https://crossroadsprograms.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Residential and community-based services for at-risk youth and young adults facing homelessness, mental health, and substance use.",
    longDesc: "Crossroads Programs serves troubled youth and young adults (ages 13–24) with a continuum of services including emergency shelter, transitional housing, independent living skills, outpatient substance use treatment, and mental health counseling. Their street outreach team works to engage homeless youth and connect them to services. Crossroads also operates a specialized program for LGBTQ+ youth who are homeless or at risk.",
    tags: ["At-Risk Youth", "Youth Shelter", "LGBTQ+ Affirming", "Ages 13-24"],
    services: ["housing", "counseling", "youth", "emergency"],
    saves: 0
  },
  {
    id: 38,
    title: "Morris County Workforce Development",
    category: "employment",
    town: "Morristown",
    address: "30 Schuyler Pl, Morristown, NJ 07960",
    phone: "(973) 285-6960",
    website: "https://morriscountynj.gov/workforce",
    hours: "Mon–Fri 8:30am–4:30pm",
    shortDesc: "Free job training, resume assistance, and employment placement for Morris County residents seeking work.",
    longDesc: "Morris County Workforce Development, operated through the One-Stop Career Center, provides a full range of employment services for job seekers. Services include career counseling, resume writing workshops, interview preparation, skills assessments, paid training programs, and job placement assistance. Priority services are available for veterans, individuals with disabilities, and long-term unemployed residents. Computer labs and internet access are available for job searching.",
    tags: ["Job Training", "Resume Help", "Career Counseling", "Free Services"],
    services: ["employment", "education"],
    saves: 0
  },
  {
    id: 39,
    title: "Homeless Prevention Program — Morris County",
    category: "housing",
    town: "Morristown",
    address: "30 Schuyler Pl, Morristown, NJ 07960",
    phone: "(973) 285-6865",
    website: "https://morriscountynj.gov",
    hours: "Mon–Fri 8:30am–4:30pm",
    shortDesc: "Emergency rental and utility assistance for Morris County residents at risk of eviction or utility shutoff.",
    longDesc: "Morris County's Homeless Prevention Program provides one-time emergency financial assistance to residents facing eviction or utility shutoff. Assistance is available for first month/last month/security deposits for those who have found housing, overdue rent, overdue utility bills, and in some cases moving costs. Eligibility is based on income and demonstration that the assistance will stabilize housing. Appointments are required and documentation must be provided.",
    tags: ["Rental Assistance", "Utility Help", "Eviction Prevention", "One-Time Aid"],
    services: ["housing", "emergency"],
    saves: 0
  },
  {
    id: 40,
    title: "SCARC — Sussex County ARC (Morris Region)",
    category: "disability",
    town: "Wharton",
    address: "11 US Highway 206, Stanhope, NJ 07874",
    phone: "(973) 347-4313",
    website: "https://scarc.org",
    hours: "Mon–Fri 8am–4pm",
    shortDesc: "Day programs, residential support, and employment services for people with developmental disabilities in northern Morris County.",
    longDesc: "SCARC provides a wide range of services for individuals with intellectual and developmental disabilities in northern New Jersey. Programs include community-based day habilitation, supported employment, group homes, family support services, and clinical services including behavioral therapy and speech-language therapy. They serve clients across the lifespan from early childhood through adulthood and work closely with families to develop individualized plans.",
    tags: ["Developmental Disabilities", "Day Habilitation", "Group Homes", "Behavioral Therapy"],
    services: ["disability", "employment"],
    saves: 0
  },
  {
    id: 41,
    title: "Open Doors — Morris County Reentry",
    category: "social-services",
    town: "Dover",
    address: "6 W Blackwell St, Dover, NJ 07801",
    phone: "(973) 361-5555",
    website: "https://opendoorsmorris.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Reentry support services for formerly incarcerated individuals including housing, employment, and case management.",
    longDesc: "Open Doors provides comprehensive reentry support for individuals being released from county jail or state prison. Services include transitional housing, employment assistance, ID and document recovery, benefits enrollment, mental health and substance use referrals, and ongoing case management. Outreach begins while clients are still incarcerated to ensure a seamless transition. Staff have lived experience and provide peer mentorship alongside professional services.",
    tags: ["Reentry Services", "Formerly Incarcerated", "ID Recovery", "Housing"],
    services: ["housing", "employment", "benefits-navigation"],
    saves: 0
  },
  {
    id: 42,
    title: "North Jersey Community Research Initiative (NJCRI)",
    category: "health",
    town: "Newark",
    address: "393 Central Ave, Newark, NJ 07103",
    phone: "(973) 483-3444",
    website: "https://njcri.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "HIV/AIDS care, harm reduction, and sexual health services accessible to Morris County residents.",
    longDesc: "NJCRI provides HIV/AIDS case management, harm reduction services, syringe access, naloxone distribution, hepatitis C testing and treatment navigation, and sexual health services. Mobile outreach teams serve communities across northern New Jersey including Morris County. Services are available regardless of insurance status, and all services are confidential. NJCRI also provides community education on HIV prevention and PrEP access.",
    tags: ["HIV/AIDS Services", "Harm Reduction", "Naloxone", "Sexual Health"],
    services: ["health"],
    saves: 0
  },
  {
    id: 43,
    title: "Dover Food Pantry",
    category: "food",
    town: "Dover",
    address: "92 N Sussex St, Dover, NJ 07801",
    phone: "(973) 366-0057",
    website: "",
    hours: "Mon, Wed, Fri 10am–12pm",
    shortDesc: "Community food pantry serving Dover and surrounding areas with grocery assistance three times per week.",
    longDesc: "The Dover Food Pantry provides free grocery assistance to residents of Dover and neighboring communities. Operating three days per week from a local church, the pantry distributes canned goods, dry staples, bread, and when available, fresh produce and dairy. Clients may visit once per week. Proof of residency is requested but not required for first-time visitors experiencing emergency need.",
    tags: ["3x Weekly", "Emergency Food", "Walk-In", "Dover Residents"],
    services: ["food", "emergency"],
    saves: 0
  },
  {
    id: 44,
    title: "Greystone Park Outpatient Services",
    category: "mental-health",
    town: "Parsippany",
    address: "59 Koch Ave, Morris Plains, NJ 07950",
    phone: "(973) 538-1800",
    website: "https://state.nj.us/humanservices",
    hours: "Mon–Fri 8am–4pm",
    shortDesc: "State-operated outpatient mental health and psychiatric services for Morris County residents on a sliding fee scale.",
    longDesc: "Greystone Park Psychiatric Hospital's outpatient department provides community mental health services for Morris County adults, including psychiatric evaluations, medication management, individual therapy, group therapy, and crisis stabilization services. Priority is given to Medicaid recipients and uninsured individuals with serious mental illness. Transportation assistance may be available for eligible clients. No one is turned away for inability to pay.",
    tags: ["Psychiatric Services", "Medication Management", "Sliding Scale", "State Funded"],
    services: ["counseling", "emergency"],
    saves: 0
  },
  {
    id: 45,
    title: "Morris County Youth Shelter",
    category: "youth",
    town: "Morristown",
    address: "314 Madison Ave, Morristown, NJ 07960",
    phone: "(973) 285-6864",
    website: "https://morriscountynj.gov",
    hours: "24/7 Crisis Line",
    shortDesc: "Emergency and transitional shelter for homeless and runaway youth ages 12–17 in Morris County.",
    longDesc: "Morris County Youth Shelter provides a safe emergency haven for youth ages 12–17 who are homeless, runaway, or in crisis. The shelter provides meals, clothing, counseling, school enrollment assistance, and family mediation services. Youth can stay for up to 21 days while case managers work toward reunification with family or transition to a longer-term placement. A 24-hour crisis line is available for youth and parents.",
    tags: ["Youth Shelter", "Ages 12-17", "24/7 Crisis Line", "Family Mediation"],
    services: ["housing", "emergency", "youth", "counseling"],
    saves: 0
  },
  {
    id: 46,
    title: "Randolph Cares Food Pantry",
    category: "food",
    town: "Randolph",
    address: "461 S Salem St, Randolph, NJ 07869",
    phone: "(973) 584-6900",
    website: "",
    hours: "First and third Sat 9am–11am",
    shortDesc: "Biweekly food pantry serving Randolph Township residents with non-perishable groceries and personal care items.",
    longDesc: "Randolph Cares operates a volunteer food pantry serving Randolph Township residents twice monthly. Clients receive a grocery package based on household size including canned goods, dry staples, and personal care products. During the holiday season, the pantry distributes special holiday meal packages. The organization also coordinates local toy drives and school supply collections for families in need.",
    tags: ["Biweekly", "Randolph Residents", "Holiday Meals", "School Supplies"],
    services: ["food"],
    saves: 0
  },
  {
    id: 47,
    title: "Bridges Outreach",
    category: "social-services",
    town: "Morristown",
    address: "14 James St, Morristown, NJ 07960",
    phone: "(973) 642-6877",
    website: "https://bridgesoutreach.net",
    hours: "Mon–Fri 8am–2pm",
    shortDesc: "Street outreach and basic needs services for chronically homeless individuals in downtown Morristown and beyond.",
    longDesc: "Bridges Outreach provides direct street outreach to homeless individuals in Morris County, meeting people where they are and providing basic needs including food, clothing, hygiene kits, and medical supplies. Their team builds trusting relationships over time to eventually connect individuals with shelter, health care, mental health treatment, and housing. They do not require sobriety or compliance with any program — harm reduction is central to their approach.",
    tags: ["Street Outreach", "Chronically Homeless", "Harm Reduction", "No Barriers"],
    services: ["food", "emergency", "housing"],
    saves: 0
  },
  {
    id: 48,
    title: "Morris Knolls High School — Student Pantry",
    category: "food",
    town: "Rockaway",
    address: "50 Knoll Dr, Rockaway, NJ 07866",
    phone: "(973) 664-2200",
    website: "",
    hours: "During school hours",
    shortDesc: "On-site food pantry for students and families of Morris Knolls High School experiencing food insecurity.",
    longDesc: "Morris Knolls High School operates a discreet on-site food pantry available to students and their families who are experiencing food insecurity. The pantry provides non-perishable snacks, meals, and household staples. Students can access items directly or be referred by school counselors or social workers. The pantry is stocked through community food drives and school fundraising. Strict confidentiality is maintained.",
    tags: ["School Pantry", "Students", "Confidential", "Snacks & Meals"],
    services: ["food", "youth"],
    saves: 0
  },
  {
    id: 49,
    title: "Disability Rights New Jersey — Morris Region",
    category: "legal",
    town: "Trenton",
    address: "210 S Broad St #701, Trenton, NJ 08608",
    phone: "(609) 292-9742",
    website: "https://drnj.org",
    hours: "Mon–Fri 9am–5pm",
    shortDesc: "Free legal advocacy for Morris County residents with disabilities facing discrimination, abuse, or denial of rights.",
    longDesc: "Disability Rights New Jersey (DRNJ) is the federally-mandated protection and advocacy organization for New Jerseyans with disabilities. They provide free legal representation and advocacy to individuals with disabilities who have experienced rights violations, including school discipline issues, Medicaid denials, nursing home or group home abuse, voting rights, and employment discrimination. DRNJ also conducts facility monitoring and systemic advocacy.",
    tags: ["Disability Rights", "Free Legal Help", "ADA", "Medicaid Appeals"],
    services: ["legal", "disability"],
    saves: 0
  },
  {
    id: 50,
    title: "Morris County NAACP — Community Resource Hotline",
    category: "social-services",
    town: "Morristown",
    address: "PO Box 1185, Morristown, NJ 07962",
    phone: "(973) 267-1441",
    website: "https://morrisnaacp.org",
    hours: "Mon, Wed, Fri 10am–2pm",
    shortDesc: "Civil rights organization providing resource navigation, advocacy, and community support for Morris County residents.",
    longDesc: "The Morris County NAACP provides civil rights advocacy, community resource navigation, and emergency support to residents facing racial discrimination, housing discrimination, police misconduct, and barriers to social services. Their resource hotline connects callers with food assistance, legal services, educational programs, and emergency aid. They also offer Know Your Rights workshops, college scholarship programs, and youth mentoring.",
    tags: ["Civil Rights", "Resource Navigation", "Advocacy", "Scholarships"],
    services: ["legal", "education", "emergency"],
    saves: 0
  }
];

// Category definitions
const CATEGORIES = [
  { id: "all",              label: "All Categories",        color: "#7A6F65" },
  { id: "food",             label: "Food & Nutrition",      color: "#C04B20" },
  { id: "housing",          label: "Housing & Shelter",     color: "#4A6741" },
  { id: "domestic-violence",label: "Domestic Violence",     color: "#8B3A3A" },
  { id: "mental-health",    label: "Mental Health",         color: "#3A5C8B" },
  { id: "substance-use",    label: "Substance Use",         color: "#6B4F8B" },
  { id: "health",           label: "Health Care",           color: "#2E7D6B" },
  { id: "legal",            label: "Legal Services",        color: "#8B6914" },
  { id: "disability",       label: "Disability Services",   color: "#4A7A8B" },
  { id: "youth",            label: "Youth & Children",      color: "#7A5C2E" },
  { id: "senior",           label: "Senior Services",       color: "#5C6B3A" },
  { id: "employment",       label: "Employment",            color: "#3A6B8B" },
  { id: "education",        label: "Education & ESL",       color: "#6B3A5C" },
  { id: "social-services",  label: "Social Services",       color: "#8B4A2E" },
];

// All unique towns
const TOWNS = [
  "All Towns",
  "Dover",
  "Flanders",
  "Morristown",
  "Morris Plains",
  "Morris Township",
  "Mount Olive",
  "Netcong",
  "Parsippany",
  "Randolph",
  "Rockaway",
  "Wharton",
  "Whippany",
];

// All service types for filtering
const SERVICE_TYPES = [
  { id: "all",                label: "All Services" },
  { id: "food",               label: "Food / Meals" },
  { id: "housing",            label: "Housing / Shelter" },
  { id: "emergency",          label: "Emergency Services" },
  { id: "counseling",         label: "Counseling / Therapy" },
  { id: "legal",              label: "Legal Aid" },
  { id: "health",             label: "Health Care" },
  { id: "employment",         label: "Employment" },
  { id: "education",          label: "Education / ESL" },
  { id: "disability",         label: "Disability Support" },
  { id: "youth",              label: "Youth Programs" },
  { id: "benefits-navigation",label: "Benefits Navigation" },
];