/* ============================================================
   CAREMAP MORRIS — Resource Data
   Community organizations in Morris County, NJ
============================================================ */

const RESOURCES = [

  // ── FOOD PANTRIES ──────────────────────────────────────────
  {
    id: 1,
    title: "Interfaith Food Pantry",
    category: "food",
    town: "Morris Plains",
    address: "2 Executive Drive, Morris Plains, NJ 07950",
    phone: "(973) 538-8049",
    website: "https://www.mcifp.org/",
    hours: "Mon–Fri: 9:30 AM – 4:30 PM",
    shortDesc: "A key food assistance provider in Morris County offering emergency and supplemental groceries, fresh produce, and nutrition support through a community-focused pantry network.",
    longDesc: "The Interfaith Food Pantry Network has worked for more than 25 years to fight hunger in Morris County, distributing millions of pounds of food and meals to people in need. It operates at a main pantry in Morris Plains and a satellite site in Morristown, offering emergency and supplemental food, free farmers markets, and a client-choice shopping model where visitors can select their own groceries. IFPN also partners with smaller pantries, providing mobile delivery programs for seniors and homebound residents, and offers nutrition education and fresh produce distributions to promote healthy eating. No one is turned away based on religion or background, and services are designed to support families, older adults, and individuals experiencing food insecurity.",
    tags: ["Food Pantry", "Client Choice", "Mobile Delivery", "Fresh Produce", "Seniors"],
    services: ["food", "emergency"],
    saves: 0
  },
  {
    id: 2,
    title: "Boonton Food Pantry",
    category: "food",
    town: "Boonton",
    address: "100 Washington Street, Boonton, NJ 07005",
    phone: "(973) 402-9410 ext 634",
    website: "https://www.boonton.org/630/Food-Pantries-Financial-Assistance",
    hours: "Mon and Fri: 2:00 PM – 5:00 PM",
    shortDesc: "A community pantry in Boonton providing supplemental groceries and essential items to local residents in need through regular weekday distribution.",
    longDesc: "The Boonton Food Pantry serves residents of Boonton by distributing free groceries and essential household items from a central location next to Town Hall. Operated by local volunteers, the pantry is open on Mondays and Fridays in the afternoon and accepts donations of non-perishable food, hygiene products, and cleaning supplies. It aims to support families and individuals facing short-term food insecurity in the community, and welcomes both monetary and item contributions to further its mission.",
    tags: ["Food Pantry", "Volunteer-Run", "Groceries", "Household Items"],
    services: ["food"],
    saves: 0
  },
  {
    id: 3,
    title: "Loaves and Fishes Community Food Pantry",
    category: "food",
    town: "Boonton",
    address: "513 Birch St., Boonton, NJ 07005",
    phone: "(973) 352-7668",
    website: "https://www.lfcfp.org/",
    hours: "Wed: 4:00 PM – 6:00 PM; Sat: 9:00 AM – 11:00 AM",
    shortDesc: "A faith-based food pantry in Boonton offering weekly food distribution to those experiencing hunger and food insecurity in the community and surrounding areas.",
    longDesc: "Loaves & Fishes Community Food Pantry is run by local churches in Boonton and provides free groceries to individuals and families struggling with food insecurity. It is open multiple days each week, and the pantry offers fresh and shelf-stable food items to anyone in need, no questions asked. It operates as a community-supported nonprofit, encouraging volunteers and donations from neighbors to help ensure consistent food access for all who visit.",
    tags: ["Food Pantry", "Faith-Based", "No Questions Asked", "Fresh Food"],
    services: ["food"],
    saves: 0
  },
  {
    id: 4,
    title: "Chester Mendham Food Pantry",
    category: "food",
    town: "Chester",
    address: "100 North Road, Chester, NJ 07930",
    phone: "(862) 419-3373",
    website: "https://www.chestermendhamfp.com/",
    hours: "Wednesdays: 9:00 AM – 11:00 AM",
    shortDesc: "A volunteer-based pantry in Chester that provides supplemental groceries, toiletries, and household supplies to residents of Chester and Mendham in need.",
    longDesc: "The Chester Mendham Food Pantry is a nonprofit organization serving neighbors in Chester and Mendham, New Jersey, by offering free supplemental food, toiletries, and essential household items. Founded through a collaboration of local community groups, the pantry operates from its location on North Road and supports dozens of families each month through food distributions and community partnerships. Volunteers help collect, sort, and deliver food, and the pantry also hosts donation drives and collaborations with local schools, churches, and businesses to meet the needs of the pantry. Services are open to those facing food insecurity, and donations of both food and monetary support are welcome to sustain operations.",
    tags: ["Food Pantry", "Volunteer-Run", "Toiletries", "Household Supplies"],
    services: ["food"],
    saves: 0
  },
  {
    id: 5,
    title: "nourish.NJ",
    category: "food",
    town: "Morristown",
    address: "36 Sussex Avenue, Morristown, NJ 07960",
    phone: "",
    website: "https://www.nourishnj.org/",
    hours: "Morristown: Mon–Fri 9:00 AM – 1:00 PM; Dover: Mon–Fri 8:00 AM – 4:00 PM",
    shortDesc: "A community-focused hunger relief organization in New Jersey that provides daily healthy meals, fresh produce, food assistance, and support services to neighbors facing food insecurity.",
    longDesc: "Nourish NJ works year-round to address hunger and its root causes by offering immediate access to nutritious food and connecting individuals and families with essential community resources. Operating multiple locations in Morris County and beyond, it provides daily meals, farmers markets, bilingual SNAP/WIC assistance, and fresh produce distributions at no cost to guests. Beyond food, Nourish NJ also supports housing stability and other social services to help people move toward lasting wellbeing. Services are offered in a welcoming, inclusive environment without income verification, and volunteers help power its mission through food distribution, meal prep, and community events.",
    tags: ["Hot Meals", "Fresh Produce", "SNAP/WIC Assistance", "Bilingual", "No Income Verification"],
    services: ["food", "emergency"],
    saves: 0
  },
  {
    id: 6,
    title: "Faith Kitchen",
    category: "food",
    town: "Dover",
    address: "123 East Blackwell Street, Dover, NJ 07801",
    phone: "(973) 219-7560",
    website: "https://www.faithkitchendover.org/",
    hours: "Mon–Sat: 11:30 AM – 12:30 PM",
    shortDesc: "A community-supported soup kitchen in Dover that serves free, nutritious meals 6 days a week while offering a welcoming space and support to neighbors experiencing hunger.",
    longDesc: "Faith Kitchen is a nonprofit soup kitchen located at Trinity Lutheran Church in Dover, New Jersey, dedicated to feeding anyone in need with free, healthy meals served Monday through Saturday around lunchtime. Supported by dozens of faith communities and volunteers, it has provided tens of thousands of meals over the years and also offers fresh produce and referrals to additional services for guests seeking help. In addition to food, Faith Kitchen fosters a friendly, inclusive environment where visitors can connect with others in the community without questions or income verification.",
    tags: ["Hot Meals", "6 Days a Week", "No Questions Asked", "Referrals"],
    services: ["food"],
    saves: 0
  },
  {
    id: 7,
    title: "Mount Olive Food Pantry",
    category: "food",
    town: "Budd Lake",
    address: "369 Sand Shore Rd, Budd Lake, NJ 07828",
    phone: "(862) 251-3938",
    website: "https://mountolivepantry.org/",
    hours: "2nd & 4th Monday: 6:30 PM – 8:00 PM; Every Tuesday: 12:00 PM – 2:30 PM; Every Saturday: 11:00 AM – 1:00 PM",
    shortDesc: "A community food pantry in Mount Olive providing free groceries and essentials to support local residents who are facing food insecurity through regular weekday and weekend distributions.",
    longDesc: "The Mount Olive Food Pantry works to reduce hunger in the Budd Lake and Mount Olive area by offering free supplemental groceries and household essentials to individuals and families whose grocery dollars are depleted. The pantry partners with local volunteers, churches, and community groups, operating multiple weekly distributions. It welcomes anyone in need, encourages community donations, and provides resources to support neighbors experiencing food insecurity.",
    tags: ["Food Pantry", "Multiple Weekly Hours", "Groceries", "Household Essentials"],
    services: ["food"],
    saves: 0
  },
  {
    id: 8,
    title: "St. Peter's Food Pantry",
    category: "food",
    town: "Parsippany",
    address: "179 Baldwin Road, Parsippany, NJ 07054",
    phone: "(973) 334-2090",
    website: "https://www.foodhelpline.org/resources/st-peter-s-food-pantry",
    hours: "Mon–Fri: 9:00 AM – 4:00 PM (call to confirm)",
    shortDesc: "A food pantry at St. Peter the Apostle in Parsippany offering free grocery assistance to local residents with scheduled weekday service by appointment.",
    longDesc: "St. Peter's Food Pantry at St. Peter The Apostle Parish in Parsippany, New Jersey provides supplemental groceries and essential food items to people experiencing food depletion. Guests can receive a month's worth of food once per month, including canned goods, produce, and dry staples. The pantry requires advance registration and appointments, and clients should bring identification, proof of address, and their own bags when visiting.",
    tags: ["Food Pantry", "By Appointment", "Monthly Visit", "Canned Goods"],
    services: ["food"],
    saves: 0
  },
  {
    id: 9,
    title: "Randolph Food Pantry",
    category: "food",
    town: "Randolph",
    address: "502 Millbrook Avenue, Randolph, NJ 07869",
    phone: "(973) 989-7100",
    website: "https://www.randolphnj.org/175/Randolph-Food-Pantry",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM (call to confirm)",
    shortDesc: "A township-operated food pantry in Randolph providing supplemental groceries and essential support to local residents experiencing food insecurity.",
    longDesc: "The Randolph Food Pantry is operated through the Randolph Township Community Services Department and provides free supplemental groceries to residents in need. The pantry supports individuals and families facing temporary or ongoing food insecurity by offering non-perishable items and other essential supplies. Services are available by scheduled appointment to ensure privacy and accessibility for clients. Community donations and local partnerships help sustain the pantry's efforts, allowing it to serve Randolph residents with dignity and care.",
    tags: ["Food Pantry", "Township-Operated", "By Appointment", "Non-Perishables"],
    services: ["food"],
    saves: 0
  },
  {
    id: 10,
    title: "Rockaway Food Closet",
    category: "food",
    town: "Rockaway",
    address: "35 Church Street, Rockaway, NJ 07866",
    phone: "(973) 627-1059",
    website: "https://fpcrockaway.org/",
    hours: "Tue–Thu: 8:30 AM – 12:30 PM; Sun: 9:00 AM – 12:30 PM",
    shortDesc: "A local community pantry at the First Presbyterian Church in Rockaway providing free non-perishable groceries and food assistance to neighbors in need.",
    longDesc: "The Rockaway Food Closet is a nonprofit organization housed at First Presbyterian Church in Rockaway, New Jersey, dedicated to helping individuals and families facing food insecurity in Rockaway Borough and Township. Volunteers collect and distribute non-perishable food items to anyone who needs them, and donations from the community help keep the shelves stocked. The pantry offers regular pick-up and drop-off hours so that residents can receive groceries and essential items with dignity and support in a welcoming environment.",
    tags: ["Food Pantry", "Non-Perishables", "Faith-Based", "Volunteer-Run"],
    services: ["food"],
    saves: 0
  },

  // ── DOMESTIC VIOLENCE ──────────────────────────────────────
  {
    id: 11,
    title: "Justia — DV Legal Aid Directory",
    category: "domestic-violence",
    town: "Morris County",
    address: "Online legal directory",
    phone: "",
    website: "https://www.justia.com/lawyers/domestic-violence/new-jersey/morris-county/legal-aid-and-pro-bono-services",
    hours: "Website accessible 24 hours a day",
    shortDesc: "An online directory listing legal aid and pro bono domestic violence attorneys and organizations serving Morris County, New Jersey.",
    longDesc: "The Justia Domestic Violence Legal Aid and Pro Bono Services page for Morris County provides a centralized directory of attorneys and nonprofit organizations that offer free or low-cost legal assistance to individuals experiencing domestic violence. The site allows users to search for services related to restraining orders, family court matters, custody issues, and other domestic violence-related legal needs. Each listing includes contact information and a brief overview of services, making it easier for residents to locate professional legal support in their area.",
    tags: ["Legal Aid", "Pro Bono", "Restraining Orders", "Family Court", "Online Directory"],
    services: ["legal"],
    saves: 0
  },
  {
    id: 12,
    title: "Morris Family Justice Center",
    category: "domestic-violence",
    town: "Morristown",
    address: "10 Court Street, 4th Floor, Morristown, NJ 07962",
    phone: "(973) 829-4050",
    website: "https://morrisfjc.org/",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM",
    shortDesc: "A walk-in resource center in Morristown where survivors of domestic violence can access coordinated support, legal help, counseling, and protection services from multiple partner agencies under one roof.",
    longDesc: "The Morris Family Justice Center provides comprehensive, coordinated services for survivors of domestic violence, dating abuse, sexual assault, and related trauma in Morris County, New Jersey. Instead of having to visit multiple agencies, individuals and families can walk into the center and receive counseling, civil legal assistance, safety planning, children's services, and immigration support with bilingual staff available. The center brings together representatives from partner agencies including Jersey Battered Women's Service, the Morris County Prosecutor's Office, legal aid organizations, and county support services in one welcoming location to streamline access to help and support.",
    tags: ["Walk-In", "Legal Advocacy", "Counseling", "Bilingual", "Safety Planning"],
    services: ["counseling", "legal", "emergency"],
    saves: 0
  },
  {
    id: 13,
    title: "Deirdre's House",
    category: "domestic-violence",
    town: "Morristown",
    address: "8 Court St, Morristown, NJ 07960",
    phone: "(973) 631-5000",
    website: "https://www.deirdreshouse.org/",
    hours: "Mon–Fri: 9:00 AM – 4:30 PM",
    shortDesc: "A child advocacy center providing abuse response, counseling, and forensic services to child victims and witnesses of violence in Morris County.",
    longDesc: "Deirdre's House serves as the central child advocacy center in Morris County for children who have experienced abuse or witnessed violence. The center offers forensic interviews, medical examinations, clinical counseling, legal support, and advocacy in a trauma-informed, child-friendly environment designed to reduce re-traumatization. In addition, Deirdre's House provides guidance for caregivers, community education programs, and prevention initiatives to strengthen families and communities, ensuring that young victims receive coordinated, compassionate care every step of the way.",
    tags: ["Child Advocacy", "Forensic Interviews", "Trauma-Informed", "Counseling"],
    services: ["counseling", "youth", "legal"],
    saves: 0
  },
  {
    id: 14,
    title: "Jersey Battered Women's Service (JBWS)",
    category: "domestic-violence",
    town: "Morristown",
    address: "Morris County Government Office, Morristown, NJ 07962",
    phone: "(973) 539-7060",
    website: "https://jbws.org/",
    hours: "Crisis Hotline: 24/7 | Admin Office: Mon–Fri 9:00 AM – 5:00 PM",
    shortDesc: "A Morris County domestic violence agency offering 24/7 crisis support, legal advocacy, shelter, and counseling for survivors and families.",
    longDesc: "Jersey Battered Women's Service (JBWS) is the leading nonprofit organization dedicated to supporting survivors of domestic violence, dating abuse, and relationship trauma in Morris County, New Jersey. JBWS provides confidential, free services including a 24-hour crisis hotline (1-877-782-2873), emergency shelter, court and legal advocacy, safety planning, counseling, and support groups. The organization also offers prevention education and community outreach programs to raise awareness and help individuals and families move toward safety and healing. Services are available to people of all backgrounds and are designed to help survivors regain stability and confidence in a supportive environment.",
    tags: ["24/7 Hotline", "Emergency Shelter", "Legal Advocacy", "Counseling", "Confidential"],
    services: ["counseling", "emergency", "legal", "housing"],
    saves: 0
  },

  // ── HOMELESS SHELTERS ──────────────────────────────────────
  {
    id: 15,
    title: "Family Promise of Morris County",
    category: "housing",
    town: "Morristown",
    address: "51 Washington St, Morristown, NJ 07960",
    phone: "(973) 998-0820",
    website: "https://www.familypromisemorris.org/",
    hours: "Mon–Thu: 11:00 AM – 3:00 PM; Outreach support: Mon–Fri 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit shelter and housing support organization in Morris County providing emergency housing, case management, and outreach services to families and individuals experiencing homelessness.",
    longDesc: "Family Promise of Morris County works to prevent and end homelessness by offering safe shelter, housing assistance, and comprehensive support services to families and individuals facing housing insecurity. Through a large network of more than 75 local congregations and volunteers, the organization provides shelter programs, transitional housing, outreach support, and case management to help guests move from crisis to permanent stability. Programs include emergency shelter via a motel model, a day-center resource hub with access to computers and basic services, coordinated outreach, and assistance with long-term housing solutions. Family Promise focuses on dignity, individualized care, and long-term success for those they serve.",
    tags: ["Family Shelter", "Case Management", "Transitional Housing", "Outreach"],
    services: ["housing", "emergency"],
    saves: 0
  },
  {
    id: 16,
    title: "Market Street Mission",
    category: "housing",
    town: "Morristown",
    address: "9 Market Street, Morristown, NJ 07960",
    phone: "(973) 538-0431",
    website: "https://www.marketstreet.org/",
    hours: "24 Hours",
    shortDesc: "A long-standing nonprofit shelter in Morristown offering emergency housing, free meals, personal care services, and supportive programs for people facing homelessness.",
    longDesc: "Market Street Mission has served the community since 1889, providing a safe place to sleep, nourishment, and supportive services to men, women, and children facing homelessness and hardship. The Mission offers overnight shelter, free daily meals, showers and personal hygiene facilities, food distribution, and holistic support designed to help people transition from crisis to stability. In addition, it provides counseling, recovery programs, life skills support, and access to clothing and household items through its thrift store — all offered free of charge. Market Street Mission's holistic approach includes spiritual and emotional care as well as essential basic needs, making it a cornerstone resource for those experiencing homelessness in Morris County and throughout northern New Jersey.",
    tags: ["Emergency Shelter", "Hot Meals", "24/7", "Recovery Programs", "Life Skills"],
    services: ["housing", "food", "counseling", "emergency"],
    saves: 0
  },
  {
    id: 17,
    title: "Homeless Solutions Inc.",
    category: "housing",
    town: "Morristown",
    address: "540 W Hanover Ave Suite 100, Morristown, NJ 07960",
    phone: "(973) 993-0900",
    website: "https://homelesssolutions.org/",
    hours: "24 Hours",
    shortDesc: "A nonprofit shelter and housing support organization in Morris County providing emergency housing, transitional programs, and services to help individuals and families experiencing homelessness move toward stability.",
    longDesc: "Homeless Solutions Inc. is a Morris County-based nonprofit dedicated to supporting people who are homeless or at risk of homelessness through a series of housing and support services. Since 1983, the organization has offered emergency overnight shelter, transitional housing programs, and affordable housing options designed to help guests achieve stability and self-sufficiency. Programs include case management, life-skills support, employment assistance, and referrals for medical, mental health, and substance use resources. Homeless Solutions works with families, single adults, and vulnerable populations to address the root causes of homelessness and empower individuals to rebuild their lives.",
    tags: ["Emergency Shelter", "Transitional Housing", "24/7", "Case Management", "Employment"],
    services: ["housing", "emergency", "employment"],
    saves: 0
  },

  // ── YOUTH & CHILDREN ───────────────────────────────────────
  {
    id: 18,
    title: "Morris Plains Teen Center",
    category: "youth",
    town: "Morris Plains",
    address: "531 Speedwell Ave, Morris Plains, NJ 07950",
    phone: "(973) 538-2224",
    website: "https://morrisplainsboro.org/teen-center/",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM",
    shortDesc: "A community teen center offering fun, supervised social events and activities for middle school students in Morris Plains.",
    longDesc: "The Morris Plains Teen Center provides local youth in grades 6–8 with a safe, supervised space to socialize and participate in community events like dances, game nights, skate nights, and other activities. The center is staffed by volunteers and supported through local partnerships and fundraising, helping teens build social skills, make positive connections, and develop a sense of belonging outside school. Programs encourage teamwork, leadership, and healthy recreation while fostering a supportive community environment.",
    tags: ["Teens", "Grades 6-8", "After-School", "Social Activities"],
    services: ["youth"],
    saves: 0
  },
  {
    id: 19,
    title: "Youth Health Resources — Rockaway Township",
    category: "youth",
    town: "Rockaway",
    address: "65 Mt. Hope Road, Rockaway, NJ 07866",
    phone: "(973) 627-7200",
    website: "https://www.rockawaytownship.org/554/Youth-Health-Resources",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM",
    shortDesc: "A local resource page offering teens and families information on mental health, healthy relationships, crisis support, and youth programs.",
    longDesc: "Rockaway Township's Youth Health Resources page provides families with trusted information and links to support the emotional, mental, and physical well-being of local teens. Topics include mental health guidance, coping strategies, healthy decision-making, suicide prevention resources like the 988 Lifeline, and connections to community programs, after-school activities, and counseling. The site helps parents and teens identify local services for youth development, safety, and resilience, ensuring families have access to timely support and education.",
    tags: ["Mental Health", "Teens", "Crisis Support", "988 Lifeline", "Family Resources"],
    services: ["youth", "counseling"],
    saves: 0
  },
  {
    id: 20,
    title: "CASA of Morris & Sussex Counties",
    category: "youth",
    town: "Cedar Knolls",
    address: "222 Ridgedale Avenue, Suite 300, Cedar Knolls, NJ 07927",
    phone: "(973) 998-7590",
    website: "https://www.casamsc.org/",
    hours: "Mon–Fri: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit that trains volunteers to advocate in family court for the safety and best interests of abused and neglected children.",
    longDesc: "CASA of Morris & Sussex Counties (Court Appointed Special Advocates) recruits and trains community volunteers to serve as advocates for children who have been abused, neglected, or placed in foster care. Each trained volunteer is assigned one child and works one-on-one to gather information, speak with teachers and caregivers, and make recommendations to the court about that child's best interests. CASA volunteers help ensure that judges have a complete picture of each child's needs so that decisions about placement, services, and long-term well-being are made with strong support and stability in mind. Through advocacy, encouragement, and ongoing involvement, CASA empowers children to have their voices heard during difficult legal proceedings.",
    tags: ["Child Advocacy", "Foster Care", "Court Advocacy", "Volunteers"],
    services: ["youth", "legal"],
    saves: 0
  },
  {
    id: 21,
    title: "Deirdre's House — Youth Services",
    category: "youth",
    town: "Morristown",
    address: "8 Court St, Morristown, NJ 07960",
    phone: "(973) 631-5000",
    website: "https://www.deirdreshouse.org/",
    hours: "Mon–Fri: 9:00 AM – 4:30 PM",
    shortDesc: "A child advocacy center providing abuse response, counseling, and forensic services to child victims and witnesses of violence in Morris County.",
    longDesc: "Deirdre's House serves as the central child advocacy center in Morris County for children who have experienced abuse or witnessed violence. The center offers forensic interviews, medical examinations, clinical counseling, legal support, and advocacy in a trauma-informed, child-friendly environment designed to reduce re-traumatization. In addition, Deirdre's House provides guidance for caregivers, community education programs, and prevention initiatives to strengthen families and communities, ensuring that young victims receive coordinated, compassionate care every step of the way.",
    tags: ["Child Advocacy", "Forensic Interviews", "Trauma-Informed", "Counseling"],
    services: ["counseling", "youth", "legal"],
    saves: 0
  },
  {
    id: 22,
    title: "Cornerstone Family Programs",
    category: "youth",
    town: "Morristown",
    address: "12 Flagler Street, Morristown, NJ 07960",
    phone: "(973) 538-1229",
    website: "https://cornerstonefamilyprograms.org/",
    hours: "Mon–Fri: 7:00 AM – 5:30 PM",
    shortDesc: "A community nonprofit in Morristown offering preschool, school-age programs, teen enrichment, and youth development services.",
    longDesc: "Cornerstone Family Programs provides children and teens with educational, recreational, and personal growth opportunities. Programs include preschool, before and after school care, summer camps, teen enrichment, college preparation, and mental health workshops. The organization focuses on fostering confidence, creativity, and leadership skills while supporting families with high-quality programs in a safe, nurturing environment. Cornerstone also connects youth with mentors, volunteers, and community resources to ensure each participant receives guidance and encouragement to thrive academically, socially, and emotionally.",
    tags: ["Preschool", "After-School", "Summer Camp", "Teen Programs", "Mental Health"],
    services: ["youth", "education", "counseling"],
    saves: 0
  },
  {
    id: 23,
    title: "Roots & Wings",
    category: "youth",
    town: "Denville",
    address: "75 Bloomfield Ave, Denville, NJ 07834",
    phone: "(973) 453-6668",
    website: "https://rootsandwingsnj.org/",
    hours: "Mon–Fri: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit empowering young adults aging out of foster care with housing, life skills, and support toward independence.",
    longDesc: "Roots & Wings provides safe housing and comprehensive support for youth transitioning out of foster care in New Jersey. Services include life skills training, educational planning, emotional and career support, and temporary coverage of rent and utilities. The organization helps participants navigate independent living, build confidence, and develop the skills needed for long-term success. Through mentorship, community engagement, and personalized guidance, Roots & Wings fosters independence while ensuring youth maintain access to critical resources and a supportive network during this vulnerable life stage.",
    tags: ["Foster Care", "Transitional Housing", "Life Skills", "Young Adults"],
    services: ["youth", "housing", "employment"],
    saves: 0
  },
  {
    id: 24,
    title: "Morris County Youth Shelter",
    category: "youth",
    town: "Morristown",
    address: "400 W Hanover Ave, Morristown, NJ 07960 (call for directions)",
    phone: "(973) 285-2970",
    website: "https://www.morriscountynj.gov/Departments/Youth-Shelter",
    hours: "24/7",
    shortDesc: "A 24/7 emergency shelter for adolescents ages 13–17 offering meals, shelter, supervision, and life-skills support.",
    longDesc: "The Morris County Youth Shelter provides safe temporary housing and structured programs for teens in crisis. Residents receive meals, recreation, education support, life skills training, and counseling in a secure, supportive environment. The shelter emphasizes stability, personal growth, and resilience, helping at-risk adolescents navigate challenges such as family conflict, homelessness, or behavioral issues. Staff work closely with families, schools, and community agencies to create individualized plans for each teen, ensuring that residents gain the tools and confidence to transition successfully back into their communities.",
    tags: ["Youth Shelter", "Ages 13-17", "24/7", "Crisis Services", "Life Skills"],
    services: ["youth", "housing", "emergency", "counseling"],
    saves: 0
  },
  {
    id: 25,
    title: "Growing Stage",
    category: "youth",
    town: "Netcong",
    address: "7 Ledgewood Avenue, Netcong, NJ 07857",
    phone: "(973) 347-4946",
    website: "https://growingstage.com/",
    hours: "Mon–Fri: 10:00 AM – 3:00 PM",
    shortDesc: "A professional children's theater in Netcong offering live performances, acting classes, and summer theater camps for kids and teens.",
    longDesc: "Growing Stage is a professional children's theater dedicated to providing high-quality theatrical performances and educational programs for youth in Morris County. The theater hosts plays and musicals designed for children and families, as well as workshops, acting classes, and summer theater camps for kids and teens of all skill levels. By combining performance opportunities with arts education, Growing Stage fosters creativity, teamwork, confidence, and self-expression while giving young people a safe, engaging environment to explore the performing arts.",
    tags: ["Youth Theater", "Arts Education", "Summer Camp", "Acting Classes"],
    services: ["youth", "education"],
    saves: 0
  },

  // ── DISABILITY SERVICES ────────────────────────────────────
  {
    id: 26,
    title: "DAWN Center for Independent Living",
    category: "disability",
    town: "Denville",
    address: "66 Ford Rd #121, Denville, NJ 07834",
    phone: "(973) 625-1940",
    website: "https://dawncil.org/",
    hours: "Mon–Fri: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit organization that helps people with disabilities live independently through advocacy, life skills training, peer support, and employment services.",
    longDesc: "The DAWN Center for Independent Living is a nonprofit organization that supports individuals with disabilities across Morris, Sussex, and Warren counties. The organization promotes independence by providing services such as advocacy, information and referrals, peer support groups, and independent living skills training. DAWN also offers employment readiness programs, recreational activities, youth transition programs, and caregiver support. By empowering individuals to define their own goals and access community resources, DAWN helps people with disabilities build independence, confidence, and full participation in their communities.",
    tags: ["Independent Living", "Peer Support", "Employment", "Advocacy", "Youth Transition"],
    services: ["disability", "employment"],
    saves: 0
  },
  {
    id: 27,
    title: "AVIDD Community Services",
    category: "disability",
    town: "Denville",
    address: "92 Broadway, Suite 101, Denville, NJ 07834",
    phone: "(973) 664-1770",
    website: "https://aviddnj.org/",
    hours: "Contact the organization for current office hours.",
    shortDesc: "A nonprofit organization that provides housing, employment training, and community support services for individuals with intellectual and developmental disabilities.",
    longDesc: "AVIDD Community Services of NJ is a nonprofit organization dedicated to supporting individuals with intellectual and developmental disabilities. Founded in 1986, the organization provides community-based services such as residential group homes, supervised apartments, employment training, and supported job placement programs. AVIDD also offers transition services for students with disabilities, recreational activities, and independent living support to help individuals build life skills and participate fully in their communities. Through personalized programs and caring staff, AVIDD works to empower people with disabilities to achieve independence, dignity, and meaningful involvement in everyday life.",
    tags: ["Group Homes", "Supported Employment", "Life Skills", "Developmental Disabilities"],
    services: ["disability", "employment", "housing"],
    saves: 0
  },
  {
    id: 28,
    title: "ArcMorris",
    category: "disability",
    town: "Morris Plains",
    address: "1 Executive Drive, Morris Plains, NJ 07950",
    phone: "(973) 326-9750",
    website: "https://arcmorris.org/",
    hours: "Mon–Fri: 8:30 AM – 5:00 PM",
    shortDesc: "A nonprofit in Morris County providing housing, employment training, and life skills programs for individuals with intellectual and developmental disabilities.",
    longDesc: "ArcMorris is a major nonprofit organization serving individuals with intellectual and developmental disabilities and their families throughout Morris County. With over 70 years of service, the organization offers a wide range of programs including residential group homes, supervised apartments, day habilitation, employment training, and recreational activities. ArcMorris also provides transition programs for youth, family support services, and clinical care to promote independence and wellbeing. Through community-based programs and personalized support, ArcMorris helps individuals build life skills, gain employment, and actively participate in their communities.",
    tags: ["Developmental Disabilities", "Group Homes", "Employment Training", "Day Habilitation"],
    services: ["disability", "employment", "housing"],
    saves: 0
  },
  {
    id: 29,
    title: "Lennon's House",
    category: "disability",
    town: "Rockaway",
    address: "21 Pine St, Rockaway, NJ 07866",
    phone: "(973) 326-9750",
    website: "https://lennonshouse.com/",
    hours: "Mon–Sun: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit organization that provides social, recreational, and life enrichment programs for individuals with developmental disabilities.",
    longDesc: "Lennon's House is a nonprofit organization based in Rockaway, New Jersey, dedicated to supporting individuals with developmental and intellectual disabilities. The organization offers social day programs, recreational activities, and community events designed to promote inclusion, friendship, and independence. Participants engage in activities such as games, volunteer opportunities, and Special Olympics programs, helping them build confidence and life skills in a supportive environment. Lennon's House also works to create a welcoming community space where individuals with disabilities can connect, grow, and participate fully in everyday life.",
    tags: ["Day Programs", "Special Olympics", "Social Activities", "Developmental Disabilities"],
    services: ["disability"],
    saves: 0
  },

  // ── EDUCATION & ESL ────────────────────────────────────────
  {
    id: 30,
    title: "Literacy Volunteers of Morris County",
    category: "education",
    town: "Morristown",
    address: "16 Elm St, 1st Floor, Morristown, NJ 07960",
    phone: "(973) 984-1998",
    website: "https://www.lvmorris.org/",
    hours: "Mon: 9:00 AM – 2:00 PM; Tue: 9:00 AM – 7:00 PM; Wed–Thu: 9:00 AM – 2:00 PM",
    shortDesc: "A nonprofit providing free ESL tutoring, literacy instruction, and citizenship preparation for adults in Morris County.",
    longDesc: "Literacy Volunteers of Morris County offers free one-on-one and small group tutoring for adults who want to improve their English reading, writing, and speaking skills. The program serves residents across more than 40 communities and includes ESL instruction, GED preparation, and citizenship support. Trained volunteer tutors work closely with students to build confidence and communication skills, helping them succeed in everyday life, work, and community involvement.",
    tags: ["ESL", "Literacy", "GED Prep", "Citizenship", "Free Tutoring"],
    services: ["education"],
    saves: 0
  },
  {
    id: 31,
    title: "Morristown & Morris Township Library — ESL Resources",
    category: "education",
    town: "Morristown",
    address: "1 Miller Rd., Morristown, NJ 07960",
    phone: "(973) 538-6161",
    website: "https://mmtlibrary.org/resources/english-as-a-second-language/",
    hours: "Mon–Thu: 9:00 AM – 9:00 PM; Fri: 9:00 AM – 5:00 PM; Sat (Sept–June): 9:00 AM – 5:00 PM; Sat (Jul–Aug): 10:00 AM – 2:00 PM; Sun: 1:00 PM – 5:00 PM",
    shortDesc: "A county library resource page listing free and low-cost ESL classes, tutoring programs, and language learning opportunities.",
    longDesc: "The Morris County Library ESL resources page connects residents with a wide range of English language learning opportunities, including free tutoring programs, adult education classes, and workforce-based ESL training. It features local programs such as Literacy Volunteers, vocational school classes, and immigrant support organizations. The page also includes both free and paid options, helping learners of all levels find accessible pathways to improve their English skills.",
    tags: ["ESL", "Adult Education", "Free Classes", "Language Learning"],
    services: ["education"],
    saves: 0
  },
  {
    id: 32,
    title: "Morris County Library — ESL Classes",
    category: "education",
    town: "Whippany",
    address: "30 East Hanover Avenue, Whippany, NJ 07981",
    phone: "(973) 285-6930",
    website: "https://www.mclib.info/Research/Local-Resources/ESL-Classes",
    hours: "Mon–Thu: 9:00 AM – 9:00 PM; Fri–Sat: 9:00 AM – 5:00 PM; Sun: Closed",
    shortDesc: "A public library offering ESL learning materials, study spaces, and access to language learning tools for adults.",
    longDesc: "The Morristown & Morris Township Library provides resources to support English language learners, including books, media kits, and online programs like Mango Languages. The library also offers study rooms and access to local ESL class information, helping learners practice reading, writing, and speaking skills. By combining educational materials with access to community programs, the library supports independent learning and skills development for non-native English speakers.",
    tags: ["ESL", "Language Learning", "Study Rooms", "Mango Languages"],
    services: ["education"],
    saves: 0
  },

  // ── HEALTH CARE ────────────────────────────────────────────
  {
    id: 33,
    title: "First Choice Women's Resource Centers",
    category: "health",
    town: "Morristown",
    address: "82 Speedwell Ave, Morristown, NJ 07960",
    phone: "(973) 538-1426",
    website: "https://1stchoice.org/",
    hours: "Mon: 8:00 AM – 4:00 PM; Wed: 8:00 AM – 4:00 PM; Thu: 9:00 AM – 6:00 PM; Fri: 11:00 AM – 3:00 PM",
    shortDesc: "A nonprofit health resource center offering free pregnancy tests, ultrasounds, STI services, and counseling for women and families.",
    longDesc: "First Choice Women's Resource Centers provides free and confidential support for people facing pregnancy-related decisions. Services include pregnancy testing, limited obstetrical ultrasounds, select STI testing, options counseling, parenting education, and material assistance such as baby and maternity items. The organization focuses on helping clients understand their options and connect with medical and social support services in a caring environment.",
    tags: ["Women's Health", "Pregnancy", "Free Services", "Confidential", "Counseling"],
    services: ["health", "counseling"],
    saves: 0
  },
  {
    id: 34,
    title: "Rockaway Neck Volunteer First Aid Squad",
    category: "health",
    town: "Parsippany",
    address: "25 Crescent Dr, Parsippany, NJ 07054",
    phone: "(973) 263-8383",
    website: "https://www.rockawayneckfirstaid.org/",
    hours: "24/7",
    shortDesc: "A volunteer emergency medical service providing 24/7 ambulance and rescue response to eastern Parsippany and Lake Hiawatha.",
    longDesc: "The Rockaway Neck First Aid Squad is a volunteer-based emergency medical service that has served the Parsippany area for decades. Staffed by certified EMTs and emergency vehicle operators, the squad provides round-the-clock ambulance and rescue services to residents in eastern Parsippany and Lake Hiawatha. Its work helps ensure rapid emergency response and community access to lifesaving pre-hospital care.",
    tags: ["Emergency Medical", "Ambulance", "24/7", "Volunteer EMTs"],
    services: ["health", "emergency"],
    saves: 0
  },
  {
    id: 35,
    title: "EdgeNJ",
    category: "health",
    town: "Parsippany",
    address: "35 Waterview Blvd Suite 201, Parsippany, NJ 07054",
    phone: "(973) 285-0006",
    website: "https://edgenj.org/",
    hours: "Mon–Thu: 8:00 AM – 8:00 PM; Fri: 8:00 AM – 5:00 PM",
    shortDesc: "A public health organization providing HIV prevention, LGBTQ+ health services, behavioral healthcare, and supportive programs in Morris County.",
    longDesc: "EDGE New Jersey advances health and wellness for HIV+ and LGBTQ+ communities through public health programs, behavioral healthcare, education, and housing support. Services include PrEP and PEP education, HIV prevention resources, harm reduction services, and access to affirming care. The organization also offers a broad range of support programs designed to improve health outcomes and connect clients with trusted resources in a welcoming environment.",
    tags: ["HIV Prevention", "LGBTQ+ Health", "Harm Reduction", "Behavioral Health", "PrEP"],
    services: ["health", "counseling"],
    saves: 0
  },
  {
    id: 36,
    title: "Community Hope",
    category: "health",
    town: "Parsippany",
    address: "959 Route 46 East, Suite 402, Parsippany, NJ 07054",
    phone: "(973) 463-9600",
    website: "https://www.communityhope-nj.org/",
    hours: "24/7",
    shortDesc: "A nonprofit organization providing mental health, addiction recovery, supportive housing, and wellness services for individuals and families in need.",
    longDesc: "Community Hope helps individuals and families facing mental illness, substance use challenges, homelessness, and poverty through a combination of behavioral health, housing, and supportive services. The organization is especially known for its mental health and recovery-focused programs, as well as services for veterans and people in crisis. By combining treatment support with stable housing and case management, Community Hope works to improve long-term health and well-being.",
    tags: ["Mental Health", "Addiction Recovery", "Veterans", "Supportive Housing", "24/7"],
    services: ["health", "counseling", "housing"],
    saves: 0
  },
  {
    id: 37,
    title: "CARE Center of New Jersey",
    category: "health",
    town: "Rockaway",
    address: "140 Green Pond Rd, Rockaway Township, NJ 07866",
    phone: "(973) 888-1256",
    website: "https://carecenterofnewjersey.org/",
    hours: "Mon–Fri: 9:00 AM – 5:00 PM",
    shortDesc: "A community nonprofit offering mental health counseling and support services to help individuals and families improve stability and well-being.",
    longDesc: "The CARE Center of New Jersey provides a mix of community and wellness services aimed at helping families build stability and healthier lives. In addition to food and clothing support, the organization offers mental health counseling, legal assistance, business development help, and other family support services. Its programs focus on reducing hardship while giving individuals access to practical resources that strengthen overall well-being.",
    tags: ["Mental Health Counseling", "Family Support", "Legal Assistance", "Community Services"],
    services: ["health", "counseling", "legal"],
    saves: 0
  },

  // ── LEGAL SERVICES ─────────────────────────────────────────
  {
    id: 38,
    title: "Legal Services of Northwest Jersey",
    category: "legal",
    town: "Morristown",
    address: "30 Schuyler Place, Morristown, NJ 07960",
    phone: "(973) 285-6911",
    website: "https://www.lsnwj.org/",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM",
    shortDesc: "A nonprofit organization providing free legal assistance to low-income residents in Morris County and surrounding areas.",
    longDesc: "Legal Services of Northwest Jersey is a nonprofit organization that provides free civil legal assistance to low-income individuals and families in Morris County and nearby regions. Services include help with housing issues such as eviction and foreclosure, family law matters including domestic violence and custody, access to public benefits, healthcare access, and consumer protection. The organization also offers legal advice, representation, and community education to help individuals understand their rights and navigate the legal system. By focusing on vulnerable populations, Legal Services of Northwest Jersey works to ensure equal access to justice and improve stability for those in need.",
    tags: ["Free Legal Aid", "Eviction Defense", "Family Law", "Benefits Appeals", "Housing"],
    services: ["legal"],
    saves: 0
  },
  {
    id: 39,
    title: "ProBono Partnership",
    category: "legal",
    town: "Parsippany",
    address: "3799 Route 46, Suite 211, Parsippany, NJ 07054",
    phone: "(973) 240-6955",
    website: "https://probonopartner.org/",
    hours: "Call for more information",
    shortDesc: "A nonprofit that provides free legal services to other nonprofits, helping them operate effectively and comply with the law.",
    longDesc: "Pro Bono Partnership connects eligible nonprofit organizations with volunteer attorneys who provide free legal assistance on a wide range of issues. Services include help with contracts, employment law, nonprofit governance, intellectual property, and regulatory compliance. While the organization does not directly represent individuals, it strengthens the nonprofit sector by ensuring that organizations serving communities — such as shelters, food pantries, and youth programs — have access to quality legal guidance. This support helps nonprofits operate more effectively and continue providing essential services.",
    tags: ["Pro Bono", "Nonprofit Legal Help", "Contracts", "Governance"],
    services: ["legal"],
    saves: 0
  },

  // ── MENTAL HEALTH ──────────────────────────────────────────
  {
    id: 40,
    title: "New Chapter Youth Program",
    category: "mental-health",
    town: "Parsippany",
    address: "1915 US-46 Suite 101, Parsippany, NJ 07054",
    phone: "(551) 209-0235",
    website: "https://newchapteryouthprogram.com/",
    hours: "Open 24 hours",
    shortDesc: "A youth-focused program providing mentorship, mental health support, and personal development services for teens.",
    longDesc: "New Chapter Youth Program supports adolescents through mentorship, mental health awareness, and personal development initiatives. The program focuses on building confidence, emotional resilience, and leadership skills while providing a safe and supportive environment for teens to express themselves. Through workshops, group sessions, and community engagement, New Chapter helps youth navigate challenges such as stress, identity, and peer pressure while promoting overall well-being.",
    tags: ["Youth", "Mentorship", "Mental Health", "Teens", "Personal Development"],
    services: ["counseling", "youth"],
    saves: 0
  },
  {
    id: 41,
    title: "Community Hope — Mental Health",
    category: "mental-health",
    town: "Parsippany",
    address: "959 Route 46 East, Suite 402, Parsippany, NJ 07054",
    phone: "(973) 463-9600",
    website: "https://www.communityhope-nj.org/",
    hours: "24/7",
    shortDesc: "A nonprofit organization providing mental health, addiction recovery, supportive housing, and wellness services for individuals and families in need.",
    longDesc: "Community Hope helps individuals and families facing mental illness, substance use challenges, homelessness, and poverty through a combination of behavioral health, housing, and supportive services. The organization is especially known for its mental health and recovery-focused programs, as well as services for veterans and people in crisis. By combining treatment support with stable housing and case management, Community Hope works to improve long-term health and well-being.",
    tags: ["Mental Health", "Addiction Recovery", "Veterans", "Supportive Housing", "24/7"],
    services: ["counseling", "housing"],
    saves: 0
  },
  {
    id: 42,
    title: "True Life Care Mental Health",
    category: "mental-health",
    town: "Morris Plains",
    address: "3000 NJ-10 Suite A, Morris Plains, NJ 07950",
    phone: "(973) 490-4563",
    website: "https://truelifecarementalhealth.com/",
    hours: "Open 24 hours",
    shortDesc: "A mental health provider offering therapy, psychiatric services, and personalized treatment plans for individuals of all ages.",
    longDesc: "True Life Care Mental Health provides outpatient mental health services including individual therapy, medication management, and treatment for conditions such as anxiety, depression, trauma, and mood disorders. The organization focuses on personalized care plans tailored to each client's needs, helping individuals improve emotional well-being and develop coping strategies. Their services aim to support long-term mental health through professional guidance and evidence-based treatment.",
    tags: ["Therapy", "Psychiatric Services", "Medication Management", "Outpatient", "All Ages"],
    services: ["counseling"],
    saves: 0
  },
  {
    id: 43,
    title: "NovaMind Wellness",
    category: "mental-health",
    town: "Denville",
    address: "3000 NJ-10 Suite C, Denville, NJ 07834",
    phone: "(973) 339-0085",
    website: "https://novamindwellness.com/",
    hours: "Open 24 hours",
    shortDesc: "A wellness center offering therapy, counseling, and holistic mental health services for individuals and families.",
    longDesc: "Nova Mind Wellness provides a range of mental health services designed to support emotional and psychological well-being. Services include individual therapy, family counseling, and holistic approaches to mental health care. The center focuses on creating a supportive environment where clients can explore challenges, build coping skills, and improve overall mental wellness through personalized and compassionate care.",
    tags: ["Therapy", "Family Counseling", "Holistic Care", "Mental Wellness"],
    services: ["counseling"],
    saves: 0
  },
  {
    id: 44,
    title: "Mental Health Association of Morris County",
    category: "mental-health",
    town: "Parsippany",
    address: "1160 Parsippany Blvd, Parsippany, NJ 07054",
    phone: "(973) 334-3496",
    website: "https://www.mhainspire.org/",
    hours: "Mon–Fri: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit organization offering mental health education, support programs, and community resources for individuals and families.",
    longDesc: "The Mental Health Association of Morris County provides a wide range of services including education, advocacy, and support programs for individuals experiencing mental health challenges. Services include support groups, youth programs, housing assistance, and community outreach initiatives. The organization works to reduce stigma, promote mental wellness, and ensure access to resources that help individuals live stable and fulfilling lives.",
    tags: ["Mental Health", "Support Groups", "Education", "Advocacy", "Youth Programs"],
    services: ["counseling", "youth"],
    saves: 0
  },

  // ── SENIOR SERVICES ────────────────────────────────────────
  {
    id: 45,
    title: "Florham Park Rehabilitation & Healthcare Center",
    category: "senior",
    town: "Florham Park",
    address: "190 Park Ave, Florham Park, NJ 07932",
    phone: "(973) 867-1500",
    website: "https://florhamparkrehab.com/",
    hours: "Open 24 hours",
    shortDesc: "A rehabilitation and nursing facility providing short-term recovery and long-term care for seniors.",
    longDesc: "Florham Park Rehabilitation and Healthcare Center offers skilled nursing care, physical therapy, and rehabilitation services for seniors recovering from illness, injury, or surgery. The facility also provides long-term care, memory care, and medical supervision for residents who require ongoing support. With a focus on recovery and quality care, the center helps seniors regain independence while ensuring comfort and safety.",
    tags: ["Senior Care", "Rehabilitation", "Skilled Nursing", "Memory Care", "24/7"],
    services: ["health"],
    saves: 0
  },
  {
    id: 46,
    title: "Sunrise Senior Living",
    category: "senior",
    town: "Morris County",
    address: "Multiple locations in Morris County",
    phone: "Varies by location",
    website: "https://www.sunriseseniorliving.com/",
    hours: "24/7 residential care",
    shortDesc: "An assisted living provider offering housing, personal care, and memory care services for seniors.",
    longDesc: "Sunrise Senior Living operates communities that provide assisted living, memory care, and short-term stays for seniors. Residents receive support with daily activities, medication management, and personalized care in a safe and comfortable environment. Programs also include social activities, wellness programs, and dining services designed to promote independence and quality of life. Sunrise focuses on creating a community atmosphere where seniors can stay active and engaged.",
    tags: ["Assisted Living", "Memory Care", "Senior Housing", "Wellness Programs"],
    services: ["health"],
    saves: 0
  },
  {
    id: 47,
    title: "Integral Home Care",
    category: "senior",
    town: "Morristown",
    address: "540 W Hanover Ave Suite 100, Morristown, NJ 07960",
    phone: "(973) 363-3200",
    website: "https://integralcarehc.com/",
    hours: "Open 24 hours",
    shortDesc: "A home care provider offering personal care, companionship, and support services for seniors and individuals with disabilities.",
    longDesc: "Integral Care Home Care Services provides non-medical support to seniors and individuals who need assistance with daily living. Services include personal care, meal preparation, transportation, and companionship. Caregivers work closely with clients and families to create customized care plans that promote independence and safety at home. The organization focuses on improving quality of life while helping individuals remain in familiar surroundings.",
    tags: ["Home Care", "Personal Care", "Companionship", "Transportation", "Seniors"],
    services: ["health"],
    saves: 0
  },
  {
    id: 48,
    title: "Excelcare at Troy Hills",
    category: "senior",
    town: "Parsippany",
    address: "200 Reynolds Ave, Parsippany, NJ 07054",
    phone: "(973) 887-8080",
    website: "https://excelcaretroyhills.com/",
    hours: "Call for more information",
    shortDesc: "A skilled nursing and rehabilitation center offering medical care, therapy, and long-term support for seniors.",
    longDesc: "Excelcare at Troy Hills provides comprehensive care for seniors, including short-term rehabilitation, long-term nursing care, and memory support services. The facility offers physical, occupational, and speech therapy along with 24-hour medical supervision. Programs are designed to help residents recover, maintain health, and improve overall well-being in a structured and supportive environment.",
    tags: ["Skilled Nursing", "Rehabilitation", "Memory Support", "Long-Term Care"],
    services: ["health"],
    saves: 0
  },
  {
    id: 49,
    title: "Caring Senior Service",
    category: "senior",
    town: "Morristown",
    address: "55 Madison Ave #400, Morristown, NJ 07960",
    phone: "(973) 447-3471",
    website: "https://caringseniorservice.com/morristown/",
    hours: "Open 24 hours",
    shortDesc: "An in-home care service providing personal assistance, companionship, and support to help seniors live independently.",
    longDesc: "Caring Senior Service of Morristown provides non-medical in-home care to seniors who want to remain safely in their own homes. Services include help with daily activities such as bathing, dressing, meal preparation, transportation, and companionship. Care plans are personalized to each individual's needs, allowing seniors to maintain independence while receiving reliable support. The organization focuses on improving quality of life and ensuring safety, comfort, and dignity for older adults.",
    tags: ["In-Home Care", "Personal Assistance", "Companionship", "Independence", "Seniors"],
    services: ["health"],
    saves: 0
  },

  // ── SUBSTANCE USE ──────────────────────────────────────────
  {
    id: 50,
    title: "Absolute Awakenings",
    category: "substance-use",
    town: "Morris Plains",
    address: "3000 NJ-10, Morris Plains, NJ 07950",
    phone: "(973) 784-8981",
    website: "https://absoluteawakenings.com/",
    hours: "Open 24 hours",
    shortDesc: "A substance abuse treatment center offering detox, therapy, and personalized recovery programs in Morris County.",
    longDesc: "Absolute Awakenings provides comprehensive addiction treatment services for individuals struggling with substance use disorders. Programs include medically supervised detox, outpatient treatment, dual-diagnosis care, and evidence-based therapies that address both addiction and underlying mental health conditions. The center uses a whole-person approach, focusing on physical, emotional, and psychological healing to support long-term recovery and prevent relapse.",
    tags: ["Detox", "Outpatient Treatment", "Dual Diagnosis", "Addiction Recovery", "24/7"],
    services: ["counseling"],
    saves: 0
  },
  {
    id: 51,
    title: "The Milestone House",
    category: "substance-use",
    town: "Dover",
    address: "60 N Sussex St, Dover, NJ 07801",
    phone: "(973) 442-4600",
    website: "https://themilestonehouse.org/donate/",
    hours: "Open 24 hours",
    shortDesc: "A nonprofit providing long-term residential recovery and sober living support for individuals overcoming addiction.",
    longDesc: "Milestone House offers structured, long-term residential programs for individuals recovering from substance use disorders. Residents receive support through counseling, peer accountability, and life-skills development, helping them transition from addiction to independent, stable living in a supportive environment.",
    tags: ["Residential Recovery", "Sober Living", "Peer Support", "Life Skills", "Long-Term"],
    services: ["counseling", "housing"],
    saves: 0
  },
  {
    id: 52,
    title: "New Pathway Counseling",
    category: "substance-use",
    town: "Pine Brook",
    address: "321 Changebridge Rd, Pine Brook, NJ 07058",
    phone: "(973) 604-3388",
    website: "https://www.newpathway.com/",
    hours: "Open 24 hours",
    shortDesc: "A counseling center offering treatment and support services for individuals dealing with substance use and mental health challenges.",
    longDesc: "New Pathway Counseling provides therapy and support for individuals struggling with substance use and co-occurring mental health conditions. Services include individual counseling, group therapy, and recovery support designed to help clients build coping skills, improve mental health, and maintain long-term sobriety.",
    tags: ["Counseling", "Group Therapy", "Substance Use", "Co-occurring Disorders", "Recovery"],
    services: ["counseling"],
    saves: 0
  },
  {
    id: 53,
    title: "Better Life Recovery & Wellness",
    category: "substance-use",
    town: "Florham Park",
    address: "25A Hanover Rd, Florham Park, NJ 07932",
    phone: "(973) 928-0175",
    website: "https://www.betterliferecovery.com/",
    hours: "Open 24 hours",
    shortDesc: "A treatment provider offering personalized addiction recovery programs and support services.",
    longDesc: "Better Life Recovery provides individualized treatment programs for substance use disorders, including therapy, counseling, and recovery planning. The organization focuses on helping individuals develop coping strategies, rebuild their lives, and achieve lasting recovery through structured and supportive care.",
    tags: ["Addiction Recovery", "Personalized Treatment", "Counseling", "Recovery Planning"],
    services: ["counseling"],
    saves: 0
  },
  {
    id: 54,
    title: "Market Street Mission — Recovery",
    category: "substance-use",
    town: "Morristown",
    address: "9 Market Street, Morristown, NJ 07960",
    phone: "(973) 538-0431",
    website: "https://www.marketstreet.org/",
    hours: "Open 24 hours",
    shortDesc: "A nonprofit offering addiction recovery programs, shelter, and support services for individuals experiencing homelessness and substance use challenges.",
    longDesc: "Market Street Mission provides long-term recovery programs for individuals struggling with addiction, combined with shelter, meals, and life-skills training. Their programs focus on personal transformation, stability, and reintegration into society by addressing both substance use and underlying life challenges.",
    tags: ["Addiction Recovery", "Shelter", "Life Skills", "Meals", "24/7"],
    services: ["counseling", "housing", "food"],
    saves: 0
  },
  {
    id: 55,
    title: "Prevention is Key (PIK)",
    category: "substance-use",
    town: "Rockaway",
    address: "25 W Main St Suite A, Rockaway, NJ 07866",
    phone: "(973) 625-1998",
    website: "https://www.preventioniskey.org/",
    hours: "Mon–Fri: 9:00 AM – 4:30 PM",
    shortDesc: "A nonprofit focused on substance use prevention, education, and recovery support programs for youth and families.",
    longDesc: "Prevention is Key works to reduce substance use through education, early intervention, and community-based programs. Services include youth prevention initiatives, recovery support, family education, and wellness programs. The organization focuses on building resilience and promoting healthy choices to prevent substance use before it begins.",
    tags: ["Prevention", "Youth Education", "Family Programs", "Recovery Support", "Wellness"],
    services: ["counseling", "youth"],
    saves: 0
  },
  {
    id: 56,
    title: "Morris County Aftercare",
    category: "substance-use",
    town: "Denville",
    address: "273 E Main St, Denville, NJ 07834",
    phone: "(973) 927-6641",
    website: "https://www.mcaftercare.org/",
    hours: "Mon–Fri: 5:30 AM – 12:30 PM; Sat: 7:00 AM – 9:00 AM",
    shortDesc: "A treatment center providing medication-assisted therapy and ongoing support for individuals recovering from opioid addiction.",
    longDesc: "Morris County Aftercare Center offers medication-assisted treatment (MAT), including methadone services, along with counseling and recovery support for individuals overcoming opioid addiction. The center focuses on long-term recovery by helping clients manage withdrawal symptoms, stabilize their lives, and rebuild healthy routines through structured care and support.",
    tags: ["Medication-Assisted Treatment", "Methadone", "Opioid Recovery", "MAT", "Counseling"],
    services: ["counseling"],
    saves: 0
  },
  {
    id: 57,
    title: "New Chapter Recovery of NJ",
    category: "substance-use",
    town: "Parsippany",
    address: "1915 US-46, Parsippany-Troy Hills, NJ 07054",
    phone: "(551) 365-4548",
    website: "https://newchapterrecoverynj.com/",
    hours: "Open 24 hours",
    shortDesc: "An outpatient recovery center providing personalized treatment programs for substance use and addiction.",
    longDesc: "New Chapter Recovery offers outpatient treatment programs for a wide range of substance use disorders, including alcohol, opioids, and prescription drugs. Services include individualized therapy, group counseling, and evidence-based treatment plans designed to support long-term recovery while allowing clients to continue daily responsibilities.",
    tags: ["Outpatient Treatment", "Alcohol Recovery", "Opioid Recovery", "Group Counseling"],
    services: ["counseling"],
    saves: 0
  }

];

// ── CATEGORY DEFINITIONS ───────────────────────────────────
const CATEGORIES = [
  { id: "all",               label: "All Categories",      color: "#7A6F65" },
  { id: "food",              label: "Food & Nutrition",    color: "#C04B20" },
  { id: "housing",           label: "Housing & Shelter",   color: "#4A6741" },
  { id: "domestic-violence", label: "Domestic Violence",   color: "#8B3A3A" },
  { id: "mental-health",     label: "Mental Health",       color: "#3A5C8B" },
  { id: "substance-use",     label: "Substance Use",       color: "#6B4F8B" },
  { id: "health",            label: "Health Care",         color: "#2E7D6B" },
  { id: "legal",             label: "Legal Services",      color: "#8B6914" },
  { id: "disability",        label: "Disability Services", color: "#4A7A8B" },
  { id: "youth",             label: "Youth & Children",    color: "#7A5C2E" },
  { id: "senior",            label: "Senior Services",     color: "#5C6B3A" },
  { id: "education",         label: "Education & ESL",     color: "#6B3A5C" },
];

// ── ALL UNIQUE TOWNS ───────────────────────────────────────
const TOWNS = [
  "All Towns",
  "Boonton",
  "Budd Lake",
  "Cedar Knolls",
  "Chester",
  "Denville",
  "Dover",
  "Florham Park",
  "Morris County",
  "Morris Plains",
  "Morristown",
  "Netcong",
  "Parsippany",
  "Pine Brook",
  "Randolph",
  "Rockaway",
  "Whippany",
];

// ── SERVICE TYPES ──────────────────────────────────────────
const SERVICE_TYPES = [
  { id: "all",                 label: "All Services" },
  { id: "food",                label: "Food / Meals" },
  { id: "housing",             label: "Housing / Shelter" },
  { id: "emergency",           label: "Emergency Services" },
  { id: "counseling",          label: "Counseling / Therapy" },
  { id: "legal",               label: "Legal Aid" },
  { id: "health",              label: "Health Care" },
  { id: "employment",          label: "Employment" },
  { id: "education",           label: "Education / ESL" },
  { id: "disability",          label: "Disability Support" },
  { id: "youth",               label: "Youth Programs" },
  { id: "benefits-navigation", label: "Benefits Navigation" },
];