/* ============================================================
   CAREMAP MORRIS — js/resources.js
   
   This file exports the RESOURCES array so it can be loaded
   by bookmarks.html, directory.html, and any other page that
   needs resource data.

   HOW TO USE:
   Add this to any page that needs resource data, BEFORE
   bookmarks.js or your directory script:
   
     <script src="js/resources.js"></script>

   Then RESOURCES is available globally.
   
   NOTE: If your directory already defines RESOURCES inline,
   you can either:
   A) Remove the inline definition and use this file instead
   B) Keep both (this file defines it as a global fallback)
============================================================ */

// Guard: don't redefine if already loaded by directory.js
if (typeof RESOURCES === 'undefined') {

var RESOURCES = [

  // ── FOOD PANTRIES ──────────────────────────────────────────
  {
    id: 1,
    title: "Interfaith Food Pantry",
    category: "food",
    town: "Morris Plains",
    address: "2 Executive Drive, Morris Plains, NJ 07950",
    phone: "(973) 538-8049",
    website: "https://www.mcifp.org/",
    hours: "Mon–Fri: 9:30 AM – 4:30 PM",
    shortDesc: "A key food assistance provider in Morris County offering emergency and supplemental groceries, fresh produce, and nutrition support through a community-focused pantry network.",
    tags: ["Food Pantry", "Client Choice", "Mobile Delivery", "Fresh Produce", "Seniors"],
    services: ["food", "emergency"],
  },
  {
    id: 2,
    title: "Boonton Food Pantry",
    category: "food",
    town: "Boonton",
    address: "100 Washington Street, Boonton, NJ 07005",
    phone: "(973) 402-9410 ext 634",
    website: "https://www.boonton.org/630/Food-Pantries-Financial-Assistance",
    hours: "Mon and Fri: 2:00 PM – 5:00 PM",
    shortDesc: "A community pantry in Boonton providing supplemental groceries and essential items to local residents in need through regular weekday distribution.",
    tags: ["Food Pantry", "Volunteer-Run", "Groceries", "Household Items"],
    services: ["food"],
  },
  {
    id: 3,
    title: "Loaves and Fishes Community Food Pantry",
    category: "food",
    town: "Boonton",
    address: "513 Birch St., Boonton, NJ 07005",
    phone: "(973) 352-7668",
    website: "https://www.lfcfp.org/",
    hours: "Wed: 4:00 PM – 6:00 PM; Sat: 9:00 AM – 11:00 AM",
    shortDesc: "A faith-based food pantry in Boonton offering weekly food distribution to those experiencing hunger and food insecurity.",
    tags: ["Food Pantry", "Faith-Based", "No Questions Asked", "Fresh Food"],
    services: ["food"],
  },
  {
    id: 4,
    title: "Chester Mendham Food Pantry",
    category: "food",
    town: "Chester",
    address: "100 North Road, Chester, NJ 07930",
    phone: "(862) 419-3373",
    website: "https://www.chestermendhamfp.com/",
    hours: "Wednesdays: 9:00 AM – 11:00 AM",
    shortDesc: "A volunteer-based pantry in Chester that provides supplemental groceries, toiletries, and household supplies to residents of Chester and Mendham.",
    tags: ["Food Pantry", "Volunteer-Run", "Toiletries", "Household Supplies"],
    services: ["food"],
  },
  {
    id: 5,
    title: "Nourish.NJ",
    category: "food",
    town: "Morristown",
    address: "36 Sussex Avenue, Morristown, NJ 07960",
    phone: "",
    website: "https://www.nourishnj.org/",
    hours: "Morristown: Mon–Fri 9:00 AM – 1:00 PM; Dover: Mon–Fri 8:00 AM – 4:00 PM",
    shortDesc: "A community-focused hunger relief organization providing daily healthy meals, fresh produce, food assistance, and support services to neighbors facing food insecurity.",
    tags: ["Hot Meals", "Fresh Produce", "SNAP/WIC Assistance", "Bilingual", "No Income Verification"],
    services: ["food", "emergency"],
  },
  {
    id: 6,
    title: "Faith Kitchen",
    category: "food",
    town: "Dover",
    address: "123 East Blackwell Street, Dover, NJ 07801",
    phone: "(973) 219-7560",
    website: "https://www.faithkitchendover.org/",
    hours: "Mon–Sat: 11:30 AM – 12:30 PM",
    shortDesc: "A community-supported soup kitchen in Dover that serves free, nutritious meals 6 days a week.",
    tags: ["Hot Meals", "6 Days a Week", "No Questions Asked", "Referrals"],
    services: ["food"],
  },
  {
    id: 7,
    title: "Mount Olive Food Pantry",
    category: "food",
    town: "Budd Lake",
    address: "369 Sand Shore Rd, Budd Lake, NJ 07828",
    phone: "(862) 251-3938",
    website: "https://mountolivepantry.org/",
    hours: "2nd & 4th Monday: 6:30 PM – 8:00 PM; Every Tuesday: 12:00 PM – 2:30 PM; Every Saturday: 11:00 AM – 1:00 PM",
    shortDesc: "A community food pantry in Mount Olive providing free groceries and essentials through regular weekday and weekend distributions.",
    tags: ["Food Pantry", "Multiple Weekly Hours", "Groceries", "Household Essentials"],
    services: ["food"],
  },
  {
    id: 8,
    title: "St. Peter's Food Pantry",
    category: "food",
    town: "Parsippany",
    address: "179 Baldwin Road, Parsippany, NJ 07054",
    phone: "(973) 334-2090",
    website: "https://www.foodhelpline.org/resources/st-peter-s-food-pantry",
    hours: "Mon–Fri: 9:00 AM – 4:00 PM (call to confirm)",
    shortDesc: "A food pantry at St. Peter the Apostle in Parsippany offering free grocery assistance with scheduled weekday service.",
    tags: ["Food Pantry", "By Appointment", "Monthly Visit", "Canned Goods"],
    services: ["food"],
  },
  {
    id: 9,
    title: "Randolph Food Pantry",
    category: "food",
    town: "Randolph",
    address: "502 Millbrook Avenue, Randolph, NJ 07869",
    phone: "(973) 989-7100",
    website: "https://www.randolphnj.org/175/Randolph-Food-Pantry",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM (call to confirm)",
    shortDesc: "A township-operated food pantry in Randolph providing supplemental groceries and essential support to local residents.",
    tags: ["Food Pantry", "Township-Operated", "By Appointment", "Non-Perishables"],
    services: ["food"],
  },
  {
    id: 10,
    title: "Rockaway Food Closet",
    category: "food",
    town: "Rockaway",
    address: "35 Church Street, Rockaway, NJ 07866",
    phone: "(973) 627-1059",
    website: "https://fpcrockaway.org/",
    hours: "Tue–Thu: 8:30 AM – 12:30 PM; Sun: 9:00 AM – 12:30 PM",
    shortDesc: "A local community pantry at the First Presbyterian Church in Rockaway providing free non-perishable groceries.",
    tags: ["Food Pantry", "Non-Perishables", "Faith-Based", "Volunteer-Run"],
    services: ["food"],
  },
  // ── DOMESTIC VIOLENCE ──────────────────────────────────────
  {
    id: 11,
    title: "Justia — DV Legal Aid Directory",
    category: "domestic-violence",
    town: "Morris County",
    address: "Online legal directory",
    phone: "",
    website: "https://www.justia.com/lawyers/domestic-violence/new-jersey/morris-county/legal-aid-and-pro-bono-services",
    hours: "Website accessible 24 hours a day",
    shortDesc: "An online directory listing legal aid and pro bono domestic violence attorneys and organizations serving Morris County.",
    tags: ["Legal Aid", "Pro Bono", "Restraining Orders", "Family Court", "Online Directory"],
    services: ["legal"],
  },
  {
    id: 12,
    title: "Morris Family Justice Center",
    category: "domestic-violence",
    town: "Morristown",
    address: "10 Court Street, 4th Floor, Morristown, NJ 07962",
    phone: "(973) 829-4050",
    website: "https://morrisfjc.org/",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM",
    shortDesc: "A walk-in resource center in Morristown where survivors can access coordinated support, legal help, counseling, and protection services.",
    tags: ["Walk-In", "Legal Advocacy", "Counseling", "Bilingual", "Safety Planning"],
    services: ["counseling", "legal", "emergency"],
  },
  {
    id: 13,
    title: "Deirdre's House",
    category: "domestic-violence",
    town: "Morristown",
    address: "8 Court St, Morristown, NJ 07960",
    phone: "(973) 631-5000",
    website: "https://www.deirdreshouse.org/",
    hours: "Mon–Fri: 9:00 AM – 4:30 PM",
    shortDesc: "A child advocacy center providing abuse response, counseling, and forensic services to child victims in Morris County.",
    tags: ["Child Advocacy", "Forensic Interviews", "Trauma-Informed", "Counseling"],
    services: ["counseling", "youth", "legal"],
  },
  {
    id: 14,
    title: "Jersey Battered Women's Service (JBWS)",
    category: "domestic-violence",
    town: "Morristown",
    address: "Morris County Government Office, Morristown, NJ 07962",
    phone: "(973) 539-7060",
    website: "https://jbws.org/",
    hours: "Crisis Hotline: 24/7 | Admin Office: Mon–Fri 9:00 AM – 5:00 PM",
    shortDesc: "A Morris County domestic violence agency offering 24/7 crisis support, legal advocacy, shelter, and counseling for survivors.",
    tags: ["24/7 Hotline", "Emergency Shelter", "Legal Advocacy", "Counseling", "Confidential"],
    services: ["counseling", "emergency", "legal", "housing"],
  },
  // ── HOUSING / SHELTER ──────────────────────────────────────
  {
    id: 15,
    title: "Family Promise of Morris County",
    category: "housing",
    town: "Morristown",
    address: "51 Washington St, Morristown, NJ 07960",
    phone: "(973) 998-0820",
    website: "https://www.familypromisemorris.org/",
    hours: "Mon–Thu: 11:00 AM – 3:00 PM",
    shortDesc: "A nonprofit shelter providing emergency housing, case management, and outreach for families experiencing homelessness.",
    tags: ["Family Shelter", "Case Management", "Transitional Housing", "Outreach"],
    services: ["housing", "emergency"],
  },
  {
    id: 16,
    title: "Market Street Mission",
    category: "housing",
    town: "Morristown",
    address: "9 Market Street, Morristown, NJ 07960",
    phone: "(973) 538-0431",
    website: "https://www.marketstreet.org/",
    hours: "24 Hours",
    shortDesc: "A long-standing nonprofit shelter offering emergency housing, free meals, and supportive programs for people facing homelessness.",
    tags: ["Emergency Shelter", "Hot Meals", "24/7", "Recovery Programs", "Life Skills"],
    services: ["housing", "food", "counseling", "emergency"],
  },
  {
    id: 17,
    title: "Homeless Solutions Inc.",
    category: "housing",
    town: "Morristown",
    address: "540 W Hanover Ave Suite 100, Morristown, NJ 07960",
    phone: "(973) 993-0900",
    website: "https://homelesssolutions.org/",
    hours: "24 Hours",
    shortDesc: "A nonprofit providing emergency housing, transitional programs, and services to help individuals and families move toward stability.",
    tags: ["Emergency Shelter", "Transitional Housing", "24/7", "Case Management", "Employment"],
    services: ["housing", "emergency", "employment"],
  },
  // ── YOUTH & CHILDREN ───────────────────────────────────────
  {
    id: 18,
    title: "Morris Plains Teen Center",
    category: "youth",
    town: "Morris Plains",
    address: "531 Speedwell Ave, Morris Plains, NJ 07950",
    phone: "(973) 538-2224",
    website: "https://morrisplainsboro.org/teen-center/",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM",
    shortDesc: "A community teen center offering supervised social events and activities for middle school students.",
    tags: ["Teens", "Grades 6-8", "After-School", "Social Activities"],
    services: ["youth"],
  },
  {
    id: 19,
    title: "Youth Health Resources — Rockaway Township",
    category: "youth",
    town: "Rockaway",
    address: "65 Mt. Hope Road, Rockaway, NJ 07866",
    phone: "(973) 627-7200",
    website: "https://www.rockawaytownship.org/554/Youth-Health-Resources",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM",
    shortDesc: "A local resource page offering teens and families information on mental health, crisis support, and youth programs.",
    tags: ["Mental Health", "Teens", "Crisis Support", "988 Lifeline", "Family Resources"],
    services: ["youth", "counseling"],
  },
  {
    id: 20,
    title: "CASA of Morris & Sussex Counties",
    category: "youth",
    town: "Cedar Knolls",
    address: "222 Ridgedale Avenue, Suite 300, Cedar Knolls, NJ 07927",
    phone: "(973) 998-7590",
    website: "https://www.casamsc.org/",
    hours: "Mon–Fri: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit that trains volunteers to advocate in family court for abused and neglected children.",
    tags: ["Child Advocacy", "Foster Care", "Court Advocacy", "Volunteers"],
    services: ["youth", "legal"],
  },
  {
    id: 21,
    title: "Deirdre's House — Youth Services",
    category: "youth",
    town: "Morristown",
    address: "8 Court St, Morristown, NJ 07960",
    phone: "(973) 631-5000",
    website: "https://www.deirdreshouse.org/",
    hours: "Mon–Fri: 9:00 AM – 4:30 PM",
    shortDesc: "A child advocacy center providing abuse response, counseling, and forensic services to child victims in Morris County.",
    tags: ["Child Advocacy", "Forensic Interviews", "Trauma-Informed", "Counseling"],
    services: ["counseling", "youth", "legal"],
  },
  {
    id: 22,
    title: "Cornerstone Family Programs",
    category: "youth",
    town: "Morristown",
    address: "12 Flagler Street, Morristown, NJ 07960",
    phone: "(973) 538-1229",
    website: "https://cornerstonefamilyprograms.org/",
    hours: "Mon–Fri: 7:00 AM – 5:30 PM",
    shortDesc: "A nonprofit offering preschool, school-age programs, teen enrichment, and youth development services.",
    tags: ["Preschool", "After-School", "Summer Camp", "Teen Programs", "Mental Health"],
    services: ["youth", "education", "counseling"],
  },
  {
    id: 23,
    title: "Roots & Wings",
    category: "youth",
    town: "Denville",
    address: "75 Bloomfield Ave, Denville, NJ 07834",
    phone: "(973) 453-6668",
    website: "https://rootsandwingsnj.org/",
    hours: "Mon–Fri: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit empowering young adults aging out of foster care with housing, life skills, and support.",
    tags: ["Foster Care", "Transitional Housing", "Life Skills", "Young Adults"],
    services: ["youth", "housing", "employment"],
  },
  {
    id: 24,
    title: "Morris County Youth Shelter",
    category: "youth",
    town: "Morristown",
    address: "400 W Hanover Ave, Morristown, NJ 07960",
    phone: "(973) 285-2970",
    website: "https://www.morriscountynj.gov/Departments/Youth-Shelter",
    hours: "24/7",
    shortDesc: "A 24/7 emergency shelter for adolescents ages 13–17 offering meals, shelter, and life-skills support.",
    tags: ["Youth Shelter", "Ages 13-17", "24/7", "Crisis Services", "Life Skills"],
    services: ["youth", "housing", "emergency", "counseling"],
  },
  {
    id: 25,
    title: "Growing Stage",
    category: "youth",
    town: "Netcong",
    address: "7 Ledgewood Avenue, Netcong, NJ 07857",
    phone: "(973) 347-4946",
    website: "https://growingstage.com/",
    hours: "Mon–Fri: 10:00 AM – 3:00 PM",
    shortDesc: "A professional children's theater offering live performances, classes, and summer camps for kids and teens.",
    tags: ["Youth Theater", "Arts Education", "Summer Camp", "Acting Classes"],
    services: ["youth", "education"],
  },
  // ── DISABILITY ─────────────────────────────────────────────
  {
    id: 26,
    title: "DAWN Center for Independent Living",
    category: "disability",
    town: "Denville",
    address: "66 Ford Rd #121, Denville, NJ 07834",
    phone: "(973) 625-1940",
    website: "https://dawncil.org/",
    hours: "Mon–Fri: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit helping people with disabilities live independently through advocacy, peer support, and employment services.",
    tags: ["Independent Living", "Peer Support", "Employment", "Advocacy", "Youth Transition"],
    services: ["disability", "employment"],
  },
  {
    id: 27,
    title: "AVIDD Community Services",
    category: "disability",
    town: "Denville",
    address: "92 Broadway, Suite 101, Denville, NJ 07834",
    phone: "(973) 664-1770",
    website: "https://aviddnj.org/",
    hours: "Contact for hours",
    shortDesc: "A nonprofit providing housing, employment training, and support for individuals with intellectual and developmental disabilities.",
    tags: ["Group Homes", "Supported Employment", "Life Skills", "Developmental Disabilities"],
    services: ["disability", "employment", "housing"],
  },
  {
    id: 28,
    title: "ArcMorris",
    category: "disability",
    town: "Morris Plains",
    address: "1 Executive Drive, Morris Plains, NJ 07950",
    phone: "(973) 326-9750",
    website: "https://arcmorris.org/",
    hours: "Mon–Fri: 8:30 AM – 5:00 PM",
    shortDesc: "A nonprofit providing housing, employment training, and life skills for individuals with intellectual and developmental disabilities.",
    tags: ["Developmental Disabilities", "Group Homes", "Employment Training", "Day Habilitation"],
    services: ["disability", "employment", "housing"],
  },
  {
    id: 29,
    title: "Lennon's House",
    category: "disability",
    town: "Rockaway",
    address: "21 Pine St, Rockaway, NJ 07866",
    phone: "(973) 326-9750",
    website: "https://lennonshouse.com/",
    hours: "Mon–Sun: 9:00 AM – 5:00 PM",
    shortDesc: "A nonprofit providing social, recreational, and life enrichment programs for individuals with developmental disabilities.",
    tags: ["Day Programs", "Special Olympics", "Social Activities", "Developmental Disabilities"],
    services: ["disability"],
  },
  // ── EDUCATION ──────────────────────────────────────────────
  {
    id: 30,
    title: "Literacy Volunteers of Morris County",
    category: "education",
    town: "Morristown",
    address: "16 Elm St, 1st Floor, Morristown, NJ 07960",
    phone: "(973) 984-1998",
    website: "https://www.lvmorris.org/",
    hours: "Mon: 9–2; Tue: 9–7; Wed–Thu: 9–2",
    shortDesc: "A nonprofit providing free ESL tutoring, literacy instruction, and citizenship preparation for adults.",
    tags: ["ESL", "Literacy", "GED Prep", "Citizenship", "Free Tutoring"],
    services: ["education"],
  },
  {
    id: 31,
    title: "Morristown & Morris Township Library",
    category: "education",
    town: "Morristown",
    address: "1 Miller Rd., Morristown, NJ 07960",
    phone: "(973) 538-6161",
    website: "https://mmtlibrary.org/resources/english-as-a-second-language/",
    hours: "Mon–Thu: 9–9; Fri: 9–5; Sat: 9–5; Sun: 1–5",
    shortDesc: "A library resource page listing free and low-cost ESL classes, tutoring programs, and language learning opportunities.",
    tags: ["ESL", "Adult Education", "Free Classes", "Language Learning"],
    services: ["education"],
  },
  {
    id: 32,
    title: "Morris County Library — ESL Classes",
    category: "education",
    town: "Whippany",
    address: "30 East Hanover Avenue, Whippany, NJ 07981",
    phone: "(973) 285-6930",
    website: "https://www.mclib.info/Research/Local-Resources/ESL-Classes",
    hours: "Mon–Thu: 9–9; Fri–Sat: 9–5",
    shortDesc: "A public library offering ESL learning materials, study spaces, and language learning tools for adults.",
    tags: ["ESL", "Language Learning", "Study Rooms", "Mango Languages"],
    services: ["education"],
  },
  // ── HEALTH ─────────────────────────────────────────────────
  {
    id: 33,
    title: "First Choice Women's Resource Centers",
    category: "health",
    town: "Morristown",
    address: "82 Speedwell Ave, Morristown, NJ 07960",
    phone: "(973) 538-1426",
    website: "https://1stchoice.org/",
    hours: "Mon & Wed: 8–4; Thu: 9–6; Fri: 11–3",
    shortDesc: "A nonprofit offering free pregnancy tests, ultrasounds, STI services, and counseling for women.",
    tags: ["Women's Health", "Pregnancy", "Free Services", "Confidential", "Counseling"],
    services: ["health", "counseling"],
  },
  {
    id: 34,
    title: "Rockaway Neck Volunteer First Aid Squad",
    category: "health",
    town: "Parsippany",
    address: "25 Crescent Dr, Parsippany, NJ 07054",
    phone: "(973) 263-8383",
    website: "https://www.rockawayneckfirstaid.org/",
    hours: "24/7",
    shortDesc: "A volunteer EMS providing 24/7 ambulance and rescue response to eastern Parsippany.",
    tags: ["Emergency Medical", "Ambulance", "24/7", "Volunteer EMTs"],
    services: ["health", "emergency"],
  },
  {
    id: 35,
    title: "EdgeNJ",
    category: "health",
    town: "Parsippany",
    address: "35 Waterview Blvd Suite 201, Parsippany, NJ 07054",
    phone: "(973) 285-0006",
    website: "https://edgenj.org/",
    hours: "Mon–Thu: 8–8; Fri: 8–5",
    shortDesc: "A public health org providing HIV prevention, LGBTQ+ health services, and behavioral healthcare.",
    tags: ["HIV Prevention", "LGBTQ+ Health", "Harm Reduction", "Behavioral Health", "PrEP"],
    services: ["health", "counseling"],
  },
  {
    id: 36,
    title: "Community Hope",
    category: "health",
    town: "Parsippany",
    address: "959 Route 46 East, Suite 402, Parsippany, NJ 07054",
    phone: "(973) 463-9600",
    website: "https://www.communityhope-nj.org/",
    hours: "24/7",
    shortDesc: "A nonprofit providing mental health, addiction recovery, supportive housing, and wellness services.",
    tags: ["Mental Health", "Addiction Recovery", "Veterans", "Supportive Housing", "24/7"],
    services: ["health", "counseling", "housing"],
  },
  {
    id: 37,
    title: "CARE Center of New Jersey",
    category: "health",
    town: "Rockaway",
    address: "140 Green Pond Rd, Rockaway Township, NJ 07866",
    phone: "(973) 888-1256",
    website: "https://carecenterofnewjersey.org/",
    hours: "Mon–Fri: 9–5",
    shortDesc: "A community nonprofit offering mental health counseling and support services.",
    tags: ["Mental Health Counseling", "Family Support", "Legal Assistance", "Community Services"],
    services: ["health", "counseling", "legal"],
  },
  // ── LEGAL ──────────────────────────────────────────────────
  {
    id: 38,
    title: "Legal Services of Northwest Jersey",
    category: "legal",
    town: "Morristown",
    address: "30 Schuyler Place, Morristown, NJ 07960",
    phone: "(973) 285-6911",
    website: "https://www.lsnwj.org/",
    hours: "Mon–Fri: 8:30 AM – 4:30 PM",
    shortDesc: "A nonprofit providing free legal assistance to low-income residents in Morris County.",
    tags: ["Free Legal Aid", "Eviction Defense", "Family Law", "Benefits Appeals", "Housing"],
    services: ["legal"],
  },
  {
    id: 39,
    title: "ProBono Partnership",
    category: "legal",
    town: "Parsippany",
    address: "3799 Route 46, Suite 211, Parsippany, NJ 07054",
    phone: "(973) 240-6955",
    website: "https://probonopartner.org/",
    hours: "Call for information",
    shortDesc: "A nonprofit providing free legal services to other nonprofits.",
    tags: ["Pro Bono", "Nonprofit Legal Help", "Contracts", "Governance"],
    services: ["legal"],
  },
  // ── MENTAL HEALTH ──────────────────────────────────────────
  {
    id: 40,
    title: "New Chapter Youth Program",
    category: "mental-health",
    town: "Parsippany",
    address: "1915 US-46 Suite 101, Parsippany, NJ 07054",
    phone: "(551) 209-0235",
    website: "https://newchapteryouthprogram.com/",
    hours: "Open 24 hours",
    shortDesc: "A youth-focused program providing mentorship, mental health support, and personal development for teens.",
    tags: ["Youth", "Mentorship", "Mental Health", "Teens", "Personal Development"],
    services: ["counseling", "youth"],
  },
  {
    id: 41,
    title: "Community Hope — Mental Health",
    category: "mental-health",
    town: "Parsippany",
    address: "959 Route 46 East, Suite 402, Parsippany, NJ 07054",
    phone: "(973) 463-9600",
    website: "https://www.communityhope-nj.org/",
    hours: "24/7",
    shortDesc: "Mental health, addiction recovery, supportive housing, and wellness services.",
    tags: ["Mental Health", "Addiction Recovery", "Veterans", "Supportive Housing", "24/7"],
    services: ["counseling", "housing"],
  },
  {
    id: 42,
    title: "True Life Care Mental Health",
    category: "mental-health",
    town: "Morris Plains",
    address: "3000 NJ-10 Suite A, Morris Plains, NJ 07950",
    phone: "(973) 490-4563",
    website: "https://truelifecarementalhealth.com/",
    hours: "Open 24 hours",
    shortDesc: "A mental health provider offering therapy, psychiatric services, and personalized treatment plans.",
    tags: ["Therapy", "Psychiatric Services", "Medication Management", "Outpatient", "All Ages"],
    services: ["counseling"],
  },
  {
    id: 44,
    title: "Mental Health Association of Morris County",
    category: "mental-health",
    town: "Parsippany",
    address: "1160 Parsippany Blvd, Parsippany, NJ 07054",
    phone: "(973) 334-3496",
    website: "https://www.mhainspire.org/",
    hours: "Mon–Fri: 9–5",
    shortDesc: "A nonprofit offering mental health education, support programs, and community resources.",
    tags: ["Mental Health", "Support Groups", "Education", "Advocacy", "Youth Programs"],
    services: ["counseling", "youth"],
  },
  // ── SENIOR ─────────────────────────────────────────────────
  {
    id: 45,
    title: "Florham Park Rehabilitation & Healthcare Center",
    category: "senior",
    town: "Florham Park",
    address: "190 Park Ave, Florham Park, NJ 07932",
    phone: "(973) 867-1500",
    website: "https://florhamparkrehab.com/",
    hours: "Open 24 hours",
    shortDesc: "A rehabilitation and nursing facility providing short-term recovery and long-term care for seniors.",
    tags: ["Senior Care", "Rehabilitation", "Skilled Nursing", "Memory Care", "24/7"],
    services: ["health"],
  },
  {
    id: 47,
    title: "Integral Home Care",
    category: "senior",
    town: "Morristown",
    address: "540 W Hanover Ave Suite 100, Morristown, NJ 07960",
    phone: "(973) 363-3200",
    website: "https://integralcarehc.com/",
    hours: "Open 24 hours",
    shortDesc: "A home care provider offering personal care, companionship, and support for seniors.",
    tags: ["Home Care", "Personal Care", "Companionship", "Transportation", "Seniors"],
    services: ["health"],
  },
  {
    id: 48,
    title: "Excelcare at Troy Hills",
    category: "senior",
    town: "Parsippany",
    address: "200 Reynolds Ave, Parsippany, NJ 07054",
    phone: "(973) 887-8080",
    website: "https://excelcaretroyhills.com/",
    hours: "Call for information",
    shortDesc: "A skilled nursing and rehabilitation center for seniors.",
    tags: ["Skilled Nursing", "Rehabilitation", "Memory Support", "Long-Term Care"],
    services: ["health"],
  },
  {
    id: 49,
    title: "Caring Senior Service",
    category: "senior",
    town: "Morristown",
    address: "55 Madison Ave #400, Morristown, NJ 07960",
    phone: "(973) 447-3471",
    website: "https://caringseniorservice.com/morristown/",
    hours: "Open 24 hours",
    shortDesc: "In-home care providing personal assistance, companionship, and support to help seniors live independently.",
    tags: ["In-Home Care", "Personal Assistance", "Companionship", "Independence", "Seniors"],
    services: ["health"],
  },
  // ── SUBSTANCE USE ──────────────────────────────────────────
  {
    id: 50,
    title: "Absolute Awakenings",
    category: "substance-use",
    town: "Morris Plains",
    address: "3000 NJ-10, Morris Plains, NJ 07950",
    phone: "(973) 784-8981",
    website: "https://absoluteawakenings.com/",
    hours: "Open 24 hours",
    shortDesc: "A substance abuse treatment center offering detox, therapy, and personalized recovery programs.",
    tags: ["Detox", "Outpatient Treatment", "Dual Diagnosis", "Addiction Recovery", "24/7"],
    services: ["counseling"],
  },
  {
    id: 51,
    title: "The Milestone House",
    category: "substance-use",
    town: "Dover",
    address: "60 N Sussex St, Dover, NJ 07801",
    phone: "(973) 442-4600",
    website: "https://themilestonehouse.org/donate/",
    hours: "Open 24 hours",
    shortDesc: "A nonprofit providing long-term residential recovery and sober living support.",
    tags: ["Residential Recovery", "Sober Living", "Peer Support", "Life Skills", "Long-Term"],
    services: ["counseling", "housing"],
  },
  {
    id: 52,
    title: "New Pathway Counseling",
    category: "substance-use",
    town: "Pine Brook",
    address: "321 Changebridge Rd, Pine Brook, NJ 07058",
    phone: "(973) 604-3388",
    website: "https://www.newpathway.com/",
    hours: "Open 24 hours",
    shortDesc: "A counseling center offering treatment for substance use and mental health challenges.",
    tags: ["Counseling", "Group Therapy", "Substance Use", "Co-occurring Disorders", "Recovery"],
    services: ["counseling"],
  },
  {
    id: 53,
    title: "Better Life Recovery & Wellness",
    category: "substance-use",
    town: "Florham Park",
    address: "25A Hanover Rd, Florham Park, NJ 07932",
    phone: "(973) 928-0175",
    website: "https://www.betterliferecovery.com/",
    hours: "Open 24 hours",
    shortDesc: "A treatment provider offering personalized addiction recovery programs.",
    tags: ["Addiction Recovery", "Personalized Treatment", "Counseling", "Recovery Planning"],
    services: ["counseling"],
  },
  {
    id: 54,
    title: "Market Street Mission — Recovery",
    category: "substance-use",
    town: "Morristown",
    address: "9 Market Street, Morristown, NJ 07960",
    phone: "(973) 538-0431",
    website: "https://www.marketstreet.org/",
    hours: "Open 24 hours",
    shortDesc: "Addiction recovery programs, shelter, and support for individuals experiencing homelessness.",
    tags: ["Addiction Recovery", "Shelter", "Life Skills", "Meals", "24/7"],
    services: ["counseling", "housing", "food"],
  },
  {
    id: 55,
    title: "Prevention is Key (PIK)",
    category: "substance-use",
    town: "Rockaway",
    address: "25 W Main St Suite A, Rockaway, NJ 07866",
    phone: "(973) 625-1998",
    website: "https://www.preventioniskey.org/",
    hours: "Mon–Fri: 9–4:30",
    shortDesc: "A nonprofit focused on substance use prevention, education, and recovery support for youth and families.",
    tags: ["Prevention", "Youth Education", "Family Programs", "Recovery Support", "Wellness"],
    services: ["counseling", "youth"],
  },
  {
    id: 56,
    title: "Morris County Aftercare",
    category: "substance-use",
    town: "Denville",
    address: "273 E Main St, Denville, NJ 07834",
    phone: "(973) 927-6641",
    website: "https://www.mcaftercare.org/",
    hours: "Mon–Fri: 5:30 AM – 12:30 PM; Sat: 7–9 AM",
    shortDesc: "Medication-assisted therapy and support for individuals recovering from opioid addiction.",
    tags: ["Medication-Assisted Treatment", "Methadone", "Opioid Recovery", "MAT", "Counseling"],
    services: ["counseling"],
  },
  {
    id: 57,
    title: "New Chapter Recovery of NJ",
    category: "substance-use",
    town: "Parsippany",
    address: "1915 US-46, Parsippany-Troy Hills, NJ 07054",
    phone: "(551) 365-4548",
    website: "https://newchapterrecoverynj.com/",
    hours: "Open 24 hours",
    shortDesc: "An outpatient recovery center with personalized treatment for substance use.",
    tags: ["Outpatient Treatment", "Alcohol Recovery", "Opioid Recovery", "Group Counseling"],
    services: ["counseling"],
  },
];

} // end guard